// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AILPJKHCGGB.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from AILPJKHCGGB.proto</summary>
  public static partial class AILPJKHCGGBReflection {

    #region Descriptor
    /// <summary>File descriptor for AILPJKHCGGB.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AILPJKHCGGBReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFBSUxQSktIQ0dHQi5wcm90bxoRTUhIRkNIQk5OR0UucHJvdG8aGE1hdGNo",
            "M0ZpbmlzaFJlYXNvbi5wcm90byJ/CgtBSUxQSktIQ0dHQhITCgtETE9ERUpC",
            "Rk5QSRgBIAEoDRIhCgtDTUlJTUpCT0JNShgFIAEoCzIMLk1ISEZDSEJOTkdF",
            "EiMKBnJlYXNvbhgLIAEoDjITLk1hdGNoM0ZpbmlzaFJlYXNvbhITCgtOQkJL",
            "TUpCR01FRhgMIAEoDUIeqgIbRWdnTGluay5EYW5oZW5nU2VydmVyLlByb3Rv",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.MHHFCHBNNGEReflection.Descriptor, global::EggLink.DanhengServer.Proto.Match3FinishReasonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.AILPJKHCGGB), global::EggLink.DanhengServer.Proto.AILPJKHCGGB.Parser, new[]{ "DLODEJBFNPI", "CMIIMJBOBMJ", "Reason", "NBBKMJBGMEF" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AILPJKHCGGB : pb::IMessage<AILPJKHCGGB>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AILPJKHCGGB> _parser = new pb::MessageParser<AILPJKHCGGB>(() => new AILPJKHCGGB());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AILPJKHCGGB> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.AILPJKHCGGBReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AILPJKHCGGB() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AILPJKHCGGB(AILPJKHCGGB other) : this() {
      dLODEJBFNPI_ = other.dLODEJBFNPI_;
      cMIIMJBOBMJ_ = other.cMIIMJBOBMJ_ != null ? other.cMIIMJBOBMJ_.Clone() : null;
      reason_ = other.reason_;
      nBBKMJBGMEF_ = other.nBBKMJBGMEF_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AILPJKHCGGB Clone() {
      return new AILPJKHCGGB(this);
    }

    /// <summary>Field number for the "DLODEJBFNPI" field.</summary>
    public const int DLODEJBFNPIFieldNumber = 1;
    private uint dLODEJBFNPI_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DLODEJBFNPI {
      get { return dLODEJBFNPI_; }
      set {
        dLODEJBFNPI_ = value;
      }
    }

    /// <summary>Field number for the "CMIIMJBOBMJ" field.</summary>
    public const int CMIIMJBOBMJFieldNumber = 5;
    private global::EggLink.DanhengServer.Proto.MHHFCHBNNGE cMIIMJBOBMJ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.MHHFCHBNNGE CMIIMJBOBMJ {
      get { return cMIIMJBOBMJ_; }
      set {
        cMIIMJBOBMJ_ = value;
      }
    }

    /// <summary>Field number for the "reason" field.</summary>
    public const int ReasonFieldNumber = 11;
    private global::EggLink.DanhengServer.Proto.Match3FinishReason reason_ = global::EggLink.DanhengServer.Proto.Match3FinishReason.Default;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.Match3FinishReason Reason {
      get { return reason_; }
      set {
        reason_ = value;
      }
    }

    /// <summary>Field number for the "NBBKMJBGMEF" field.</summary>
    public const int NBBKMJBGMEFFieldNumber = 12;
    private uint nBBKMJBGMEF_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NBBKMJBGMEF {
      get { return nBBKMJBGMEF_; }
      set {
        nBBKMJBGMEF_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AILPJKHCGGB);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AILPJKHCGGB other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DLODEJBFNPI != other.DLODEJBFNPI) return false;
      if (!object.Equals(CMIIMJBOBMJ, other.CMIIMJBOBMJ)) return false;
      if (Reason != other.Reason) return false;
      if (NBBKMJBGMEF != other.NBBKMJBGMEF) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DLODEJBFNPI != 0) hash ^= DLODEJBFNPI.GetHashCode();
      if (cMIIMJBOBMJ_ != null) hash ^= CMIIMJBOBMJ.GetHashCode();
      if (Reason != global::EggLink.DanhengServer.Proto.Match3FinishReason.Default) hash ^= Reason.GetHashCode();
      if (NBBKMJBGMEF != 0) hash ^= NBBKMJBGMEF.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DLODEJBFNPI != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(DLODEJBFNPI);
      }
      if (cMIIMJBOBMJ_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(CMIIMJBOBMJ);
      }
      if (Reason != global::EggLink.DanhengServer.Proto.Match3FinishReason.Default) {
        output.WriteRawTag(88);
        output.WriteEnum((int) Reason);
      }
      if (NBBKMJBGMEF != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(NBBKMJBGMEF);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DLODEJBFNPI != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(DLODEJBFNPI);
      }
      if (cMIIMJBOBMJ_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(CMIIMJBOBMJ);
      }
      if (Reason != global::EggLink.DanhengServer.Proto.Match3FinishReason.Default) {
        output.WriteRawTag(88);
        output.WriteEnum((int) Reason);
      }
      if (NBBKMJBGMEF != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(NBBKMJBGMEF);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DLODEJBFNPI != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DLODEJBFNPI);
      }
      if (cMIIMJBOBMJ_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CMIIMJBOBMJ);
      }
      if (Reason != global::EggLink.DanhengServer.Proto.Match3FinishReason.Default) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Reason);
      }
      if (NBBKMJBGMEF != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NBBKMJBGMEF);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AILPJKHCGGB other) {
      if (other == null) {
        return;
      }
      if (other.DLODEJBFNPI != 0) {
        DLODEJBFNPI = other.DLODEJBFNPI;
      }
      if (other.cMIIMJBOBMJ_ != null) {
        if (cMIIMJBOBMJ_ == null) {
          CMIIMJBOBMJ = new global::EggLink.DanhengServer.Proto.MHHFCHBNNGE();
        }
        CMIIMJBOBMJ.MergeFrom(other.CMIIMJBOBMJ);
      }
      if (other.Reason != global::EggLink.DanhengServer.Proto.Match3FinishReason.Default) {
        Reason = other.Reason;
      }
      if (other.NBBKMJBGMEF != 0) {
        NBBKMJBGMEF = other.NBBKMJBGMEF;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DLODEJBFNPI = input.ReadUInt32();
            break;
          }
          case 42: {
            if (cMIIMJBOBMJ_ == null) {
              CMIIMJBOBMJ = new global::EggLink.DanhengServer.Proto.MHHFCHBNNGE();
            }
            input.ReadMessage(CMIIMJBOBMJ);
            break;
          }
          case 88: {
            Reason = (global::EggLink.DanhengServer.Proto.Match3FinishReason) input.ReadEnum();
            break;
          }
          case 96: {
            NBBKMJBGMEF = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            DLODEJBFNPI = input.ReadUInt32();
            break;
          }
          case 42: {
            if (cMIIMJBOBMJ_ == null) {
              CMIIMJBOBMJ = new global::EggLink.DanhengServer.Proto.MHHFCHBNNGE();
            }
            input.ReadMessage(CMIIMJBOBMJ);
            break;
          }
          case 88: {
            Reason = (global::EggLink.DanhengServer.Proto.Match3FinishReason) input.ReadEnum();
            break;
          }
          case 96: {
            NBBKMJBGMEF = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
