// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AKBABFFAIDA.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from AKBABFFAIDA.proto</summary>
  public static partial class AKBABFFAIDAReflection {

    #region Descriptor
    /// <summary>File descriptor for AKBABFFAIDA.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AKBABFFAIDAReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFBS0JBQkZGQUlEQS5wcm90bxoRRlBGQ0hGQU5OR0gucHJvdG8aEUdNTkpK",
            "TURDTEhILnByb3RvGhFMQ0xESUhGTEpLSC5wcm90byKwAQoLQUtCQUJGRkFJ",
            "REESIQoLRkhNRU9NUEJNRksYAyABKAsyDC5MQ0xESUhGTEpLSBIRCgltYXhf",
            "dGltZXMYBSABKA0SIQoLREVNS0NOSURESkYYBiABKAsyDC5HTU5KSk1EQ0xI",
            "SBIMCgRuYW1lGAcgASgJEhoKBGRhdGEYCCABKAsyDC5GUEZDSEZBTk5HSBIM",
            "CgR0aW1lGAogASgDEhAKCGVuZF90aW1lGA8gASgDQh6qAhtFZ2dMaW5rLkRh",
            "bmhlbmdTZXJ2ZXIuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.FPFCHFANNGHReflection.Descriptor, global::EggLink.DanhengServer.Proto.GMNJJMDCLHHReflection.Descriptor, global::EggLink.DanhengServer.Proto.LCLDIHFLJKHReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.AKBABFFAIDA), global::EggLink.DanhengServer.Proto.AKBABFFAIDA.Parser, new[]{ "FHMEOMPBMFK", "MaxTimes", "DEMKCNIDDJF", "Name", "Data", "Time", "EndTime" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AKBABFFAIDA : pb::IMessage<AKBABFFAIDA>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AKBABFFAIDA> _parser = new pb::MessageParser<AKBABFFAIDA>(() => new AKBABFFAIDA());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AKBABFFAIDA> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.AKBABFFAIDAReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AKBABFFAIDA() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AKBABFFAIDA(AKBABFFAIDA other) : this() {
      fHMEOMPBMFK_ = other.fHMEOMPBMFK_ != null ? other.fHMEOMPBMFK_.Clone() : null;
      maxTimes_ = other.maxTimes_;
      dEMKCNIDDJF_ = other.dEMKCNIDDJF_ != null ? other.dEMKCNIDDJF_.Clone() : null;
      name_ = other.name_;
      data_ = other.data_ != null ? other.data_.Clone() : null;
      time_ = other.time_;
      endTime_ = other.endTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AKBABFFAIDA Clone() {
      return new AKBABFFAIDA(this);
    }

    /// <summary>Field number for the "FHMEOMPBMFK" field.</summary>
    public const int FHMEOMPBMFKFieldNumber = 3;
    private global::EggLink.DanhengServer.Proto.LCLDIHFLJKH fHMEOMPBMFK_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.LCLDIHFLJKH FHMEOMPBMFK {
      get { return fHMEOMPBMFK_; }
      set {
        fHMEOMPBMFK_ = value;
      }
    }

    /// <summary>Field number for the "max_times" field.</summary>
    public const int MaxTimesFieldNumber = 5;
    private uint maxTimes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MaxTimes {
      get { return maxTimes_; }
      set {
        maxTimes_ = value;
      }
    }

    /// <summary>Field number for the "DEMKCNIDDJF" field.</summary>
    public const int DEMKCNIDDJFFieldNumber = 6;
    private global::EggLink.DanhengServer.Proto.GMNJJMDCLHH dEMKCNIDDJF_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.GMNJJMDCLHH DEMKCNIDDJF {
      get { return dEMKCNIDDJF_; }
      set {
        dEMKCNIDDJF_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 7;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 8;
    private global::EggLink.DanhengServer.Proto.FPFCHFANNGH data_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.FPFCHFANNGH Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 10;
    private long time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "end_time" field.</summary>
    public const int EndTimeFieldNumber = 15;
    private long endTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long EndTime {
      get { return endTime_; }
      set {
        endTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AKBABFFAIDA);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AKBABFFAIDA other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(FHMEOMPBMFK, other.FHMEOMPBMFK)) return false;
      if (MaxTimes != other.MaxTimes) return false;
      if (!object.Equals(DEMKCNIDDJF, other.DEMKCNIDDJF)) return false;
      if (Name != other.Name) return false;
      if (!object.Equals(Data, other.Data)) return false;
      if (Time != other.Time) return false;
      if (EndTime != other.EndTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (fHMEOMPBMFK_ != null) hash ^= FHMEOMPBMFK.GetHashCode();
      if (MaxTimes != 0) hash ^= MaxTimes.GetHashCode();
      if (dEMKCNIDDJF_ != null) hash ^= DEMKCNIDDJF.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      if (Time != 0L) hash ^= Time.GetHashCode();
      if (EndTime != 0L) hash ^= EndTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (fHMEOMPBMFK_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(FHMEOMPBMFK);
      }
      if (MaxTimes != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(MaxTimes);
      }
      if (dEMKCNIDDJF_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(DEMKCNIDDJF);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Name);
      }
      if (data_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Data);
      }
      if (Time != 0L) {
        output.WriteRawTag(80);
        output.WriteInt64(Time);
      }
      if (EndTime != 0L) {
        output.WriteRawTag(120);
        output.WriteInt64(EndTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (fHMEOMPBMFK_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(FHMEOMPBMFK);
      }
      if (MaxTimes != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(MaxTimes);
      }
      if (dEMKCNIDDJF_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(DEMKCNIDDJF);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Name);
      }
      if (data_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Data);
      }
      if (Time != 0L) {
        output.WriteRawTag(80);
        output.WriteInt64(Time);
      }
      if (EndTime != 0L) {
        output.WriteRawTag(120);
        output.WriteInt64(EndTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (fHMEOMPBMFK_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FHMEOMPBMFK);
      }
      if (MaxTimes != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MaxTimes);
      }
      if (dEMKCNIDDJF_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DEMKCNIDDJF);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (Time != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Time);
      }
      if (EndTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(EndTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AKBABFFAIDA other) {
      if (other == null) {
        return;
      }
      if (other.fHMEOMPBMFK_ != null) {
        if (fHMEOMPBMFK_ == null) {
          FHMEOMPBMFK = new global::EggLink.DanhengServer.Proto.LCLDIHFLJKH();
        }
        FHMEOMPBMFK.MergeFrom(other.FHMEOMPBMFK);
      }
      if (other.MaxTimes != 0) {
        MaxTimes = other.MaxTimes;
      }
      if (other.dEMKCNIDDJF_ != null) {
        if (dEMKCNIDDJF_ == null) {
          DEMKCNIDDJF = new global::EggLink.DanhengServer.Proto.GMNJJMDCLHH();
        }
        DEMKCNIDDJF.MergeFrom(other.DEMKCNIDDJF);
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::EggLink.DanhengServer.Proto.FPFCHFANNGH();
        }
        Data.MergeFrom(other.Data);
      }
      if (other.Time != 0L) {
        Time = other.Time;
      }
      if (other.EndTime != 0L) {
        EndTime = other.EndTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 26: {
            if (fHMEOMPBMFK_ == null) {
              FHMEOMPBMFK = new global::EggLink.DanhengServer.Proto.LCLDIHFLJKH();
            }
            input.ReadMessage(FHMEOMPBMFK);
            break;
          }
          case 40: {
            MaxTimes = input.ReadUInt32();
            break;
          }
          case 50: {
            if (dEMKCNIDDJF_ == null) {
              DEMKCNIDDJF = new global::EggLink.DanhengServer.Proto.GMNJJMDCLHH();
            }
            input.ReadMessage(DEMKCNIDDJF);
            break;
          }
          case 58: {
            Name = input.ReadString();
            break;
          }
          case 66: {
            if (data_ == null) {
              Data = new global::EggLink.DanhengServer.Proto.FPFCHFANNGH();
            }
            input.ReadMessage(Data);
            break;
          }
          case 80: {
            Time = input.ReadInt64();
            break;
          }
          case 120: {
            EndTime = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 26: {
            if (fHMEOMPBMFK_ == null) {
              FHMEOMPBMFK = new global::EggLink.DanhengServer.Proto.LCLDIHFLJKH();
            }
            input.ReadMessage(FHMEOMPBMFK);
            break;
          }
          case 40: {
            MaxTimes = input.ReadUInt32();
            break;
          }
          case 50: {
            if (dEMKCNIDDJF_ == null) {
              DEMKCNIDDJF = new global::EggLink.DanhengServer.Proto.GMNJJMDCLHH();
            }
            input.ReadMessage(DEMKCNIDDJF);
            break;
          }
          case 58: {
            Name = input.ReadString();
            break;
          }
          case 66: {
            if (data_ == null) {
              Data = new global::EggLink.DanhengServer.Proto.FPFCHFANNGH();
            }
            input.ReadMessage(Data);
            break;
          }
          case 80: {
            Time = input.ReadInt64();
            break;
          }
          case 120: {
            EndTime = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
