// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BHOHMBFAIOO.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from BHOHMBFAIOO.proto</summary>
  public static partial class BHOHMBFAIOOReflection {

    #region Descriptor
    /// <summary>File descriptor for BHOHMBFAIOO.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BHOHMBFAIOOReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFCSE9ITUJGQUlPTy5wcm90bypkCgtCSE9ITUJGQUlPTxIbChdCSE9ITUJG",
            "QUlPT19QQkRLQk9BQ0pCSBAAEhsKF0JIT0hNQkZBSU9PX0tMSEtGSERJUE5B",
            "EAESGwoXQkhPSE1CRkFJT09fQUZGTVBPQkZKSUsQAkIeqgIbRWdnTGluay5E",
            "YW5oZW5nU2VydmVyLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::EggLink.DanhengServer.Proto.BHOHMBFAIOO), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum BHOHMBFAIOO {
    [pbr::OriginalName("BHOHMBFAIOO_PBDKBOACJBH")] Pbdkboacjbh = 0,
    [pbr::OriginalName("BHOHMBFAIOO_KLHKFHDIPNA")] Klhkfhdipna = 1,
    [pbr::OriginalName("BHOHMBFAIOO_AFFMPOBFJIK")] Affmpobfjik = 2,
  }

  #endregion

}

#endregion Designer generated code
