// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BKMKGJHIDJN.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from BKMKGJHIDJN.proto</summary>
  public static partial class BKMKGJHIDJNReflection {

    #region Descriptor
    /// <summary>File descriptor for BKMKGJHIDJN.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BKMKGJHIDJNReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFCS01LR0pISURKTi5wcm90byoxCgtCS01LR0pISURKThIRCg1OT1JNQUxf",
            "Q1JFQVRFEAASDwoLRk9STV9DSEFOR0UQAUIeqgIbRWdnTGluay5EYW5oZW5n",
            "U2VydmVyLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::EggLink.DanhengServer.Proto.BKMKGJHIDJN), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum BKMKGJHIDJN {
    [pbr::OriginalName("NORMAL_CREATE")] NormalCreate = 0,
    [pbr::OriginalName("FORM_CHANGE")] FormChange = 1,
  }

  #endregion

}

#endregion Designer generated code
