// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CDKJNODKDLM.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from CDKJNODKDLM.proto</summary>
  public static partial class CDKJNODKDLMReflection {

    #region Descriptor
    /// <summary>File descriptor for CDKJNODKDLM.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CDKJNODKDLMReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFDREtKTk9ES0RMTS5wcm90bxoRQ05MTk5KRERFR00ucHJvdG8aEURQQ0hF",
            "SE5IQ0dPLnByb3RvGhFFRE9GQktIR1BBQy5wcm90bxoRRUxMTURBRUZCRkUu",
            "cHJvdG8aEUdOS01DSk9GTUdCLnByb3RvGhFJSE5NTkNMSU9EQy5wcm90bxoR",
            "SUlEUEhIREJGTE8ucHJvdG8aEUpBT0JKRkpOTEZHLnByb3RvGhFKR01KSlBN",
            "SktJUC5wcm90bxoRT09OREhET0FCTEUucHJvdG8aEVBNQklHT0FEQktOLnBy",
            "b3RvIssDCgtDREtKTk9ES0RMTRIhCgtFS0ZJSUJLSkxFRhgBIAEoCzIMLkVE",
            "T0ZCS0hHUEFDEhMKC0xBTEJNTkJBS0tBGAIgASgNEiEKC0tHQkxJUEtERk5J",
            "GAMgASgLMgwuQ05MTk5KRERFR00SIQoLTkxNUEJORFBDTkgYBSABKAsyDC5E",
            "UENIRUhOSENHTxIhCgtOR0dFQ0xBRkNKRxgGIAEoCzIMLkVMTE1EQUVGQkZF",
            "EiEKC0JGQkZMR0FOUEhLGAcgASgLMgwuUE1CSUdPQURCS04SIQoLR0lQR0xK",
            "S0pES0EYCCADKAsyDC5JSE5NTkNMSU9EQxIcCgZzdGF0dXMYCiABKA4yDC5H",
            "TktNQ0pPRk1HQhIPCgdhcmVhX2lkGAsgASgNEiEKC0tBRURMQUJKRENBGAwg",
            "AygLMgwuSkFPQkpGSk5MRkcSGAoQZGlmZmljdWx0eV9sZXZlbBgNIAEoDRIh",
            "CgtHQ0xFS0lMRUNCSRgPIAEoCzIMLklJRFBISERCRkxPEiIKC0lGTEVHR05Q",
            "TkJNGPcJIAEoCzIMLkpHTUpKUE1KS0lQEiIKC0VLRkRJRktMS0FQGJUKIAEo",
            "CzIMLk9PTkRIRE9BQkxFQh6qAhtFZ2dMaW5rLkRhbmhlbmdTZXJ2ZXIuUHJv",
            "dG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.CNLNNJDDEGMReflection.Descriptor, global::EggLink.DanhengServer.Proto.DPCHEHNHCGOReflection.Descriptor, global::EggLink.DanhengServer.Proto.EDOFBKHGPACReflection.Descriptor, global::EggLink.DanhengServer.Proto.ELLMDAEFBFEReflection.Descriptor, global::EggLink.DanhengServer.Proto.GNKMCJOFMGBReflection.Descriptor, global::EggLink.DanhengServer.Proto.IHNMNCLIODCReflection.Descriptor, global::EggLink.DanhengServer.Proto.IIDPHHDBFLOReflection.Descriptor, global::EggLink.DanhengServer.Proto.JAOBJFJNLFGReflection.Descriptor, global::EggLink.DanhengServer.Proto.JGMJJPMJKIPReflection.Descriptor, global::EggLink.DanhengServer.Proto.OONDHDOABLEReflection.Descriptor, global::EggLink.DanhengServer.Proto.PMBIGOADBKNReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.CDKJNODKDLM), global::EggLink.DanhengServer.Proto.CDKJNODKDLM.Parser, new[]{ "EKFIIBKJLEF", "LALBMNBAKKA", "KGBLIPKDFNI", "NLMPBNDPCNH", "NGGECLAFCJG", "BFBFLGANPHK", "GIPGLJKJDKA", "Status", "AreaId", "KAEDLABJDCA", "DifficultyLevel", "GCLEKILECBI", "IFLEGGNPNBM", "EKFDIFKLKAP" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CDKJNODKDLM : pb::IMessage<CDKJNODKDLM>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CDKJNODKDLM> _parser = new pb::MessageParser<CDKJNODKDLM>(() => new CDKJNODKDLM());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CDKJNODKDLM> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.CDKJNODKDLMReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CDKJNODKDLM() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CDKJNODKDLM(CDKJNODKDLM other) : this() {
      eKFIIBKJLEF_ = other.eKFIIBKJLEF_ != null ? other.eKFIIBKJLEF_.Clone() : null;
      lALBMNBAKKA_ = other.lALBMNBAKKA_;
      kGBLIPKDFNI_ = other.kGBLIPKDFNI_ != null ? other.kGBLIPKDFNI_.Clone() : null;
      nLMPBNDPCNH_ = other.nLMPBNDPCNH_ != null ? other.nLMPBNDPCNH_.Clone() : null;
      nGGECLAFCJG_ = other.nGGECLAFCJG_ != null ? other.nGGECLAFCJG_.Clone() : null;
      bFBFLGANPHK_ = other.bFBFLGANPHK_ != null ? other.bFBFLGANPHK_.Clone() : null;
      gIPGLJKJDKA_ = other.gIPGLJKJDKA_.Clone();
      status_ = other.status_;
      areaId_ = other.areaId_;
      kAEDLABJDCA_ = other.kAEDLABJDCA_.Clone();
      difficultyLevel_ = other.difficultyLevel_;
      gCLEKILECBI_ = other.gCLEKILECBI_ != null ? other.gCLEKILECBI_.Clone() : null;
      iFLEGGNPNBM_ = other.iFLEGGNPNBM_ != null ? other.iFLEGGNPNBM_.Clone() : null;
      eKFDIFKLKAP_ = other.eKFDIFKLKAP_ != null ? other.eKFDIFKLKAP_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CDKJNODKDLM Clone() {
      return new CDKJNODKDLM(this);
    }

    /// <summary>Field number for the "EKFIIBKJLEF" field.</summary>
    public const int EKFIIBKJLEFFieldNumber = 1;
    private global::EggLink.DanhengServer.Proto.EDOFBKHGPAC eKFIIBKJLEF_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.EDOFBKHGPAC EKFIIBKJLEF {
      get { return eKFIIBKJLEF_; }
      set {
        eKFIIBKJLEF_ = value;
      }
    }

    /// <summary>Field number for the "LALBMNBAKKA" field.</summary>
    public const int LALBMNBAKKAFieldNumber = 2;
    private uint lALBMNBAKKA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LALBMNBAKKA {
      get { return lALBMNBAKKA_; }
      set {
        lALBMNBAKKA_ = value;
      }
    }

    /// <summary>Field number for the "KGBLIPKDFNI" field.</summary>
    public const int KGBLIPKDFNIFieldNumber = 3;
    private global::EggLink.DanhengServer.Proto.CNLNNJDDEGM kGBLIPKDFNI_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.CNLNNJDDEGM KGBLIPKDFNI {
      get { return kGBLIPKDFNI_; }
      set {
        kGBLIPKDFNI_ = value;
      }
    }

    /// <summary>Field number for the "NLMPBNDPCNH" field.</summary>
    public const int NLMPBNDPCNHFieldNumber = 5;
    private global::EggLink.DanhengServer.Proto.DPCHEHNHCGO nLMPBNDPCNH_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.DPCHEHNHCGO NLMPBNDPCNH {
      get { return nLMPBNDPCNH_; }
      set {
        nLMPBNDPCNH_ = value;
      }
    }

    /// <summary>Field number for the "NGGECLAFCJG" field.</summary>
    public const int NGGECLAFCJGFieldNumber = 6;
    private global::EggLink.DanhengServer.Proto.ELLMDAEFBFE nGGECLAFCJG_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.ELLMDAEFBFE NGGECLAFCJG {
      get { return nGGECLAFCJG_; }
      set {
        nGGECLAFCJG_ = value;
      }
    }

    /// <summary>Field number for the "BFBFLGANPHK" field.</summary>
    public const int BFBFLGANPHKFieldNumber = 7;
    private global::EggLink.DanhengServer.Proto.PMBIGOADBKN bFBFLGANPHK_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.PMBIGOADBKN BFBFLGANPHK {
      get { return bFBFLGANPHK_; }
      set {
        bFBFLGANPHK_ = value;
      }
    }

    /// <summary>Field number for the "GIPGLJKJDKA" field.</summary>
    public const int GIPGLJKJDKAFieldNumber = 8;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.IHNMNCLIODC> _repeated_gIPGLJKJDKA_codec
        = pb::FieldCodec.ForMessage(66, global::EggLink.DanhengServer.Proto.IHNMNCLIODC.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.IHNMNCLIODC> gIPGLJKJDKA_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.IHNMNCLIODC>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.IHNMNCLIODC> GIPGLJKJDKA {
      get { return gIPGLJKJDKA_; }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 10;
    private global::EggLink.DanhengServer.Proto.GNKMCJOFMGB status_ = global::EggLink.DanhengServer.Proto.GNKMCJOFMGB.Alocmfakbkp;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.GNKMCJOFMGB Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "area_id" field.</summary>
    public const int AreaIdFieldNumber = 11;
    private uint areaId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AreaId {
      get { return areaId_; }
      set {
        areaId_ = value;
      }
    }

    /// <summary>Field number for the "KAEDLABJDCA" field.</summary>
    public const int KAEDLABJDCAFieldNumber = 12;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.JAOBJFJNLFG> _repeated_kAEDLABJDCA_codec
        = pb::FieldCodec.ForMessage(98, global::EggLink.DanhengServer.Proto.JAOBJFJNLFG.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.JAOBJFJNLFG> kAEDLABJDCA_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.JAOBJFJNLFG>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.JAOBJFJNLFG> KAEDLABJDCA {
      get { return kAEDLABJDCA_; }
    }

    /// <summary>Field number for the "difficulty_level" field.</summary>
    public const int DifficultyLevelFieldNumber = 13;
    private uint difficultyLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DifficultyLevel {
      get { return difficultyLevel_; }
      set {
        difficultyLevel_ = value;
      }
    }

    /// <summary>Field number for the "GCLEKILECBI" field.</summary>
    public const int GCLEKILECBIFieldNumber = 15;
    private global::EggLink.DanhengServer.Proto.IIDPHHDBFLO gCLEKILECBI_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.IIDPHHDBFLO GCLEKILECBI {
      get { return gCLEKILECBI_; }
      set {
        gCLEKILECBI_ = value;
      }
    }

    /// <summary>Field number for the "IFLEGGNPNBM" field.</summary>
    public const int IFLEGGNPNBMFieldNumber = 1271;
    private global::EggLink.DanhengServer.Proto.JGMJJPMJKIP iFLEGGNPNBM_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.JGMJJPMJKIP IFLEGGNPNBM {
      get { return iFLEGGNPNBM_; }
      set {
        iFLEGGNPNBM_ = value;
      }
    }

    /// <summary>Field number for the "EKFDIFKLKAP" field.</summary>
    public const int EKFDIFKLKAPFieldNumber = 1301;
    private global::EggLink.DanhengServer.Proto.OONDHDOABLE eKFDIFKLKAP_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.OONDHDOABLE EKFDIFKLKAP {
      get { return eKFDIFKLKAP_; }
      set {
        eKFDIFKLKAP_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CDKJNODKDLM);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CDKJNODKDLM other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(EKFIIBKJLEF, other.EKFIIBKJLEF)) return false;
      if (LALBMNBAKKA != other.LALBMNBAKKA) return false;
      if (!object.Equals(KGBLIPKDFNI, other.KGBLIPKDFNI)) return false;
      if (!object.Equals(NLMPBNDPCNH, other.NLMPBNDPCNH)) return false;
      if (!object.Equals(NGGECLAFCJG, other.NGGECLAFCJG)) return false;
      if (!object.Equals(BFBFLGANPHK, other.BFBFLGANPHK)) return false;
      if(!gIPGLJKJDKA_.Equals(other.gIPGLJKJDKA_)) return false;
      if (Status != other.Status) return false;
      if (AreaId != other.AreaId) return false;
      if(!kAEDLABJDCA_.Equals(other.kAEDLABJDCA_)) return false;
      if (DifficultyLevel != other.DifficultyLevel) return false;
      if (!object.Equals(GCLEKILECBI, other.GCLEKILECBI)) return false;
      if (!object.Equals(IFLEGGNPNBM, other.IFLEGGNPNBM)) return false;
      if (!object.Equals(EKFDIFKLKAP, other.EKFDIFKLKAP)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (eKFIIBKJLEF_ != null) hash ^= EKFIIBKJLEF.GetHashCode();
      if (LALBMNBAKKA != 0) hash ^= LALBMNBAKKA.GetHashCode();
      if (kGBLIPKDFNI_ != null) hash ^= KGBLIPKDFNI.GetHashCode();
      if (nLMPBNDPCNH_ != null) hash ^= NLMPBNDPCNH.GetHashCode();
      if (nGGECLAFCJG_ != null) hash ^= NGGECLAFCJG.GetHashCode();
      if (bFBFLGANPHK_ != null) hash ^= BFBFLGANPHK.GetHashCode();
      hash ^= gIPGLJKJDKA_.GetHashCode();
      if (Status != global::EggLink.DanhengServer.Proto.GNKMCJOFMGB.Alocmfakbkp) hash ^= Status.GetHashCode();
      if (AreaId != 0) hash ^= AreaId.GetHashCode();
      hash ^= kAEDLABJDCA_.GetHashCode();
      if (DifficultyLevel != 0) hash ^= DifficultyLevel.GetHashCode();
      if (gCLEKILECBI_ != null) hash ^= GCLEKILECBI.GetHashCode();
      if (iFLEGGNPNBM_ != null) hash ^= IFLEGGNPNBM.GetHashCode();
      if (eKFDIFKLKAP_ != null) hash ^= EKFDIFKLKAP.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (eKFIIBKJLEF_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(EKFIIBKJLEF);
      }
      if (LALBMNBAKKA != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(LALBMNBAKKA);
      }
      if (kGBLIPKDFNI_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(KGBLIPKDFNI);
      }
      if (nLMPBNDPCNH_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(NLMPBNDPCNH);
      }
      if (nGGECLAFCJG_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(NGGECLAFCJG);
      }
      if (bFBFLGANPHK_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(BFBFLGANPHK);
      }
      gIPGLJKJDKA_.WriteTo(output, _repeated_gIPGLJKJDKA_codec);
      if (Status != global::EggLink.DanhengServer.Proto.GNKMCJOFMGB.Alocmfakbkp) {
        output.WriteRawTag(80);
        output.WriteEnum((int) Status);
      }
      if (AreaId != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(AreaId);
      }
      kAEDLABJDCA_.WriteTo(output, _repeated_kAEDLABJDCA_codec);
      if (DifficultyLevel != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(DifficultyLevel);
      }
      if (gCLEKILECBI_ != null) {
        output.WriteRawTag(122);
        output.WriteMessage(GCLEKILECBI);
      }
      if (iFLEGGNPNBM_ != null) {
        output.WriteRawTag(186, 79);
        output.WriteMessage(IFLEGGNPNBM);
      }
      if (eKFDIFKLKAP_ != null) {
        output.WriteRawTag(170, 81);
        output.WriteMessage(EKFDIFKLKAP);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (eKFIIBKJLEF_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(EKFIIBKJLEF);
      }
      if (LALBMNBAKKA != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(LALBMNBAKKA);
      }
      if (kGBLIPKDFNI_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(KGBLIPKDFNI);
      }
      if (nLMPBNDPCNH_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(NLMPBNDPCNH);
      }
      if (nGGECLAFCJG_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(NGGECLAFCJG);
      }
      if (bFBFLGANPHK_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(BFBFLGANPHK);
      }
      gIPGLJKJDKA_.WriteTo(ref output, _repeated_gIPGLJKJDKA_codec);
      if (Status != global::EggLink.DanhengServer.Proto.GNKMCJOFMGB.Alocmfakbkp) {
        output.WriteRawTag(80);
        output.WriteEnum((int) Status);
      }
      if (AreaId != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(AreaId);
      }
      kAEDLABJDCA_.WriteTo(ref output, _repeated_kAEDLABJDCA_codec);
      if (DifficultyLevel != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(DifficultyLevel);
      }
      if (gCLEKILECBI_ != null) {
        output.WriteRawTag(122);
        output.WriteMessage(GCLEKILECBI);
      }
      if (iFLEGGNPNBM_ != null) {
        output.WriteRawTag(186, 79);
        output.WriteMessage(IFLEGGNPNBM);
      }
      if (eKFDIFKLKAP_ != null) {
        output.WriteRawTag(170, 81);
        output.WriteMessage(EKFDIFKLKAP);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (eKFIIBKJLEF_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EKFIIBKJLEF);
      }
      if (LALBMNBAKKA != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LALBMNBAKKA);
      }
      if (kGBLIPKDFNI_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(KGBLIPKDFNI);
      }
      if (nLMPBNDPCNH_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NLMPBNDPCNH);
      }
      if (nGGECLAFCJG_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NGGECLAFCJG);
      }
      if (bFBFLGANPHK_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BFBFLGANPHK);
      }
      size += gIPGLJKJDKA_.CalculateSize(_repeated_gIPGLJKJDKA_codec);
      if (Status != global::EggLink.DanhengServer.Proto.GNKMCJOFMGB.Alocmfakbkp) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (AreaId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AreaId);
      }
      size += kAEDLABJDCA_.CalculateSize(_repeated_kAEDLABJDCA_codec);
      if (DifficultyLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DifficultyLevel);
      }
      if (gCLEKILECBI_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GCLEKILECBI);
      }
      if (iFLEGGNPNBM_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(IFLEGGNPNBM);
      }
      if (eKFDIFKLKAP_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(EKFDIFKLKAP);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CDKJNODKDLM other) {
      if (other == null) {
        return;
      }
      if (other.eKFIIBKJLEF_ != null) {
        if (eKFIIBKJLEF_ == null) {
          EKFIIBKJLEF = new global::EggLink.DanhengServer.Proto.EDOFBKHGPAC();
        }
        EKFIIBKJLEF.MergeFrom(other.EKFIIBKJLEF);
      }
      if (other.LALBMNBAKKA != 0) {
        LALBMNBAKKA = other.LALBMNBAKKA;
      }
      if (other.kGBLIPKDFNI_ != null) {
        if (kGBLIPKDFNI_ == null) {
          KGBLIPKDFNI = new global::EggLink.DanhengServer.Proto.CNLNNJDDEGM();
        }
        KGBLIPKDFNI.MergeFrom(other.KGBLIPKDFNI);
      }
      if (other.nLMPBNDPCNH_ != null) {
        if (nLMPBNDPCNH_ == null) {
          NLMPBNDPCNH = new global::EggLink.DanhengServer.Proto.DPCHEHNHCGO();
        }
        NLMPBNDPCNH.MergeFrom(other.NLMPBNDPCNH);
      }
      if (other.nGGECLAFCJG_ != null) {
        if (nGGECLAFCJG_ == null) {
          NGGECLAFCJG = new global::EggLink.DanhengServer.Proto.ELLMDAEFBFE();
        }
        NGGECLAFCJG.MergeFrom(other.NGGECLAFCJG);
      }
      if (other.bFBFLGANPHK_ != null) {
        if (bFBFLGANPHK_ == null) {
          BFBFLGANPHK = new global::EggLink.DanhengServer.Proto.PMBIGOADBKN();
        }
        BFBFLGANPHK.MergeFrom(other.BFBFLGANPHK);
      }
      gIPGLJKJDKA_.Add(other.gIPGLJKJDKA_);
      if (other.Status != global::EggLink.DanhengServer.Proto.GNKMCJOFMGB.Alocmfakbkp) {
        Status = other.Status;
      }
      if (other.AreaId != 0) {
        AreaId = other.AreaId;
      }
      kAEDLABJDCA_.Add(other.kAEDLABJDCA_);
      if (other.DifficultyLevel != 0) {
        DifficultyLevel = other.DifficultyLevel;
      }
      if (other.gCLEKILECBI_ != null) {
        if (gCLEKILECBI_ == null) {
          GCLEKILECBI = new global::EggLink.DanhengServer.Proto.IIDPHHDBFLO();
        }
        GCLEKILECBI.MergeFrom(other.GCLEKILECBI);
      }
      if (other.iFLEGGNPNBM_ != null) {
        if (iFLEGGNPNBM_ == null) {
          IFLEGGNPNBM = new global::EggLink.DanhengServer.Proto.JGMJJPMJKIP();
        }
        IFLEGGNPNBM.MergeFrom(other.IFLEGGNPNBM);
      }
      if (other.eKFDIFKLKAP_ != null) {
        if (eKFDIFKLKAP_ == null) {
          EKFDIFKLKAP = new global::EggLink.DanhengServer.Proto.OONDHDOABLE();
        }
        EKFDIFKLKAP.MergeFrom(other.EKFDIFKLKAP);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (eKFIIBKJLEF_ == null) {
              EKFIIBKJLEF = new global::EggLink.DanhengServer.Proto.EDOFBKHGPAC();
            }
            input.ReadMessage(EKFIIBKJLEF);
            break;
          }
          case 16: {
            LALBMNBAKKA = input.ReadUInt32();
            break;
          }
          case 26: {
            if (kGBLIPKDFNI_ == null) {
              KGBLIPKDFNI = new global::EggLink.DanhengServer.Proto.CNLNNJDDEGM();
            }
            input.ReadMessage(KGBLIPKDFNI);
            break;
          }
          case 42: {
            if (nLMPBNDPCNH_ == null) {
              NLMPBNDPCNH = new global::EggLink.DanhengServer.Proto.DPCHEHNHCGO();
            }
            input.ReadMessage(NLMPBNDPCNH);
            break;
          }
          case 50: {
            if (nGGECLAFCJG_ == null) {
              NGGECLAFCJG = new global::EggLink.DanhengServer.Proto.ELLMDAEFBFE();
            }
            input.ReadMessage(NGGECLAFCJG);
            break;
          }
          case 58: {
            if (bFBFLGANPHK_ == null) {
              BFBFLGANPHK = new global::EggLink.DanhengServer.Proto.PMBIGOADBKN();
            }
            input.ReadMessage(BFBFLGANPHK);
            break;
          }
          case 66: {
            gIPGLJKJDKA_.AddEntriesFrom(input, _repeated_gIPGLJKJDKA_codec);
            break;
          }
          case 80: {
            Status = (global::EggLink.DanhengServer.Proto.GNKMCJOFMGB) input.ReadEnum();
            break;
          }
          case 88: {
            AreaId = input.ReadUInt32();
            break;
          }
          case 98: {
            kAEDLABJDCA_.AddEntriesFrom(input, _repeated_kAEDLABJDCA_codec);
            break;
          }
          case 104: {
            DifficultyLevel = input.ReadUInt32();
            break;
          }
          case 122: {
            if (gCLEKILECBI_ == null) {
              GCLEKILECBI = new global::EggLink.DanhengServer.Proto.IIDPHHDBFLO();
            }
            input.ReadMessage(GCLEKILECBI);
            break;
          }
          case 10170: {
            if (iFLEGGNPNBM_ == null) {
              IFLEGGNPNBM = new global::EggLink.DanhengServer.Proto.JGMJJPMJKIP();
            }
            input.ReadMessage(IFLEGGNPNBM);
            break;
          }
          case 10410: {
            if (eKFDIFKLKAP_ == null) {
              EKFDIFKLKAP = new global::EggLink.DanhengServer.Proto.OONDHDOABLE();
            }
            input.ReadMessage(EKFDIFKLKAP);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (eKFIIBKJLEF_ == null) {
              EKFIIBKJLEF = new global::EggLink.DanhengServer.Proto.EDOFBKHGPAC();
            }
            input.ReadMessage(EKFIIBKJLEF);
            break;
          }
          case 16: {
            LALBMNBAKKA = input.ReadUInt32();
            break;
          }
          case 26: {
            if (kGBLIPKDFNI_ == null) {
              KGBLIPKDFNI = new global::EggLink.DanhengServer.Proto.CNLNNJDDEGM();
            }
            input.ReadMessage(KGBLIPKDFNI);
            break;
          }
          case 42: {
            if (nLMPBNDPCNH_ == null) {
              NLMPBNDPCNH = new global::EggLink.DanhengServer.Proto.DPCHEHNHCGO();
            }
            input.ReadMessage(NLMPBNDPCNH);
            break;
          }
          case 50: {
            if (nGGECLAFCJG_ == null) {
              NGGECLAFCJG = new global::EggLink.DanhengServer.Proto.ELLMDAEFBFE();
            }
            input.ReadMessage(NGGECLAFCJG);
            break;
          }
          case 58: {
            if (bFBFLGANPHK_ == null) {
              BFBFLGANPHK = new global::EggLink.DanhengServer.Proto.PMBIGOADBKN();
            }
            input.ReadMessage(BFBFLGANPHK);
            break;
          }
          case 66: {
            gIPGLJKJDKA_.AddEntriesFrom(ref input, _repeated_gIPGLJKJDKA_codec);
            break;
          }
          case 80: {
            Status = (global::EggLink.DanhengServer.Proto.GNKMCJOFMGB) input.ReadEnum();
            break;
          }
          case 88: {
            AreaId = input.ReadUInt32();
            break;
          }
          case 98: {
            kAEDLABJDCA_.AddEntriesFrom(ref input, _repeated_kAEDLABJDCA_codec);
            break;
          }
          case 104: {
            DifficultyLevel = input.ReadUInt32();
            break;
          }
          case 122: {
            if (gCLEKILECBI_ == null) {
              GCLEKILECBI = new global::EggLink.DanhengServer.Proto.IIDPHHDBFLO();
            }
            input.ReadMessage(GCLEKILECBI);
            break;
          }
          case 10170: {
            if (iFLEGGNPNBM_ == null) {
              IFLEGGNPNBM = new global::EggLink.DanhengServer.Proto.JGMJJPMJKIP();
            }
            input.ReadMessage(IFLEGGNPNBM);
            break;
          }
          case 10410: {
            if (eKFDIFKLKAP_ == null) {
              EKFDIFKLKAP = new global::EggLink.DanhengServer.Proto.OONDHDOABLE();
            }
            input.ReadMessage(EKFDIFKLKAP);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
