// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ChessRogueStartCsReq.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from ChessRogueStartCsReq.proto</summary>
  public static partial class ChessRogueStartCsReqReflection {

    #region Descriptor
    /// <summary>File descriptor for ChessRogueStartCsReq.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChessRogueStartCsReqReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpDaGVzc1JvZ3VlU3RhcnRDc1JlcS5wcm90byLBAQoUQ2hlc3NSb2d1ZVN0",
            "YXJ0Q3NSZXESEQoJYnJhbmNoX2lkGAggASgNEhwKFHRyaWFsX2F2YXRhcl9p",
            "ZF9saXN0GA4gAygNEg8KB2Flb25faWQYBSABKA0SIAoYc3RhcnRfZGlmZmlj",
            "dWx0eV9pZF9saXN0GAIgAygNEhsKE2Jhc2VfYXZhdGFyX2lkX2xpc3QYByAD",
            "KA0SHAoUZGlzYWJsZV9hZW9uX2lkX2xpc3QYDSADKA0SCgoCaWQYAyABKA1C",
            "HqoCG0VnZ0xpbmsuRGFuaGVuZ1NlcnZlci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.ChessRogueStartCsReq), global::EggLink.DanhengServer.Proto.ChessRogueStartCsReq.Parser, new[]{ "BranchId", "TrialAvatarIdList", "AeonId", "StartDifficultyIdList", "BaseAvatarIdList", "DisableAeonIdList", "Id" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ChessRogueStartCsReq : pb::IMessage<ChessRogueStartCsReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChessRogueStartCsReq> _parser = new pb::MessageParser<ChessRogueStartCsReq>(() => new ChessRogueStartCsReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChessRogueStartCsReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.ChessRogueStartCsReqReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChessRogueStartCsReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChessRogueStartCsReq(ChessRogueStartCsReq other) : this() {
      branchId_ = other.branchId_;
      trialAvatarIdList_ = other.trialAvatarIdList_.Clone();
      aeonId_ = other.aeonId_;
      startDifficultyIdList_ = other.startDifficultyIdList_.Clone();
      baseAvatarIdList_ = other.baseAvatarIdList_.Clone();
      disableAeonIdList_ = other.disableAeonIdList_.Clone();
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChessRogueStartCsReq Clone() {
      return new ChessRogueStartCsReq(this);
    }

    /// <summary>Field number for the "branch_id" field.</summary>
    public const int BranchIdFieldNumber = 8;
    private uint branchId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BranchId {
      get { return branchId_; }
      set {
        branchId_ = value;
      }
    }

    /// <summary>Field number for the "trial_avatar_id_list" field.</summary>
    public const int TrialAvatarIdListFieldNumber = 14;
    private static readonly pb::FieldCodec<uint> _repeated_trialAvatarIdList_codec
        = pb::FieldCodec.ForUInt32(114);
    private readonly pbc::RepeatedField<uint> trialAvatarIdList_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> TrialAvatarIdList {
      get { return trialAvatarIdList_; }
    }

    /// <summary>Field number for the "aeon_id" field.</summary>
    public const int AeonIdFieldNumber = 5;
    private uint aeonId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AeonId {
      get { return aeonId_; }
      set {
        aeonId_ = value;
      }
    }

    /// <summary>Field number for the "start_difficulty_id_list" field.</summary>
    public const int StartDifficultyIdListFieldNumber = 2;
    private static readonly pb::FieldCodec<uint> _repeated_startDifficultyIdList_codec
        = pb::FieldCodec.ForUInt32(18);
    private readonly pbc::RepeatedField<uint> startDifficultyIdList_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> StartDifficultyIdList {
      get { return startDifficultyIdList_; }
    }

    /// <summary>Field number for the "base_avatar_id_list" field.</summary>
    public const int BaseAvatarIdListFieldNumber = 7;
    private static readonly pb::FieldCodec<uint> _repeated_baseAvatarIdList_codec
        = pb::FieldCodec.ForUInt32(58);
    private readonly pbc::RepeatedField<uint> baseAvatarIdList_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> BaseAvatarIdList {
      get { return baseAvatarIdList_; }
    }

    /// <summary>Field number for the "disable_aeon_id_list" field.</summary>
    public const int DisableAeonIdListFieldNumber = 13;
    private static readonly pb::FieldCodec<uint> _repeated_disableAeonIdList_codec
        = pb::FieldCodec.ForUInt32(106);
    private readonly pbc::RepeatedField<uint> disableAeonIdList_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> DisableAeonIdList {
      get { return disableAeonIdList_; }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 3;
    private uint id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChessRogueStartCsReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChessRogueStartCsReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BranchId != other.BranchId) return false;
      if(!trialAvatarIdList_.Equals(other.trialAvatarIdList_)) return false;
      if (AeonId != other.AeonId) return false;
      if(!startDifficultyIdList_.Equals(other.startDifficultyIdList_)) return false;
      if(!baseAvatarIdList_.Equals(other.baseAvatarIdList_)) return false;
      if(!disableAeonIdList_.Equals(other.disableAeonIdList_)) return false;
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BranchId != 0) hash ^= BranchId.GetHashCode();
      hash ^= trialAvatarIdList_.GetHashCode();
      if (AeonId != 0) hash ^= AeonId.GetHashCode();
      hash ^= startDifficultyIdList_.GetHashCode();
      hash ^= baseAvatarIdList_.GetHashCode();
      hash ^= disableAeonIdList_.GetHashCode();
      if (Id != 0) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      startDifficultyIdList_.WriteTo(output, _repeated_startDifficultyIdList_codec);
      if (Id != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Id);
      }
      if (AeonId != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(AeonId);
      }
      baseAvatarIdList_.WriteTo(output, _repeated_baseAvatarIdList_codec);
      if (BranchId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(BranchId);
      }
      disableAeonIdList_.WriteTo(output, _repeated_disableAeonIdList_codec);
      trialAvatarIdList_.WriteTo(output, _repeated_trialAvatarIdList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      startDifficultyIdList_.WriteTo(ref output, _repeated_startDifficultyIdList_codec);
      if (Id != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Id);
      }
      if (AeonId != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(AeonId);
      }
      baseAvatarIdList_.WriteTo(ref output, _repeated_baseAvatarIdList_codec);
      if (BranchId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(BranchId);
      }
      disableAeonIdList_.WriteTo(ref output, _repeated_disableAeonIdList_codec);
      trialAvatarIdList_.WriteTo(ref output, _repeated_trialAvatarIdList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BranchId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BranchId);
      }
      size += trialAvatarIdList_.CalculateSize(_repeated_trialAvatarIdList_codec);
      if (AeonId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AeonId);
      }
      size += startDifficultyIdList_.CalculateSize(_repeated_startDifficultyIdList_codec);
      size += baseAvatarIdList_.CalculateSize(_repeated_baseAvatarIdList_codec);
      size += disableAeonIdList_.CalculateSize(_repeated_disableAeonIdList_codec);
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChessRogueStartCsReq other) {
      if (other == null) {
        return;
      }
      if (other.BranchId != 0) {
        BranchId = other.BranchId;
      }
      trialAvatarIdList_.Add(other.trialAvatarIdList_);
      if (other.AeonId != 0) {
        AeonId = other.AeonId;
      }
      startDifficultyIdList_.Add(other.startDifficultyIdList_);
      baseAvatarIdList_.Add(other.baseAvatarIdList_);
      disableAeonIdList_.Add(other.disableAeonIdList_);
      if (other.Id != 0) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18:
          case 16: {
            startDifficultyIdList_.AddEntriesFrom(input, _repeated_startDifficultyIdList_codec);
            break;
          }
          case 24: {
            Id = input.ReadUInt32();
            break;
          }
          case 40: {
            AeonId = input.ReadUInt32();
            break;
          }
          case 58:
          case 56: {
            baseAvatarIdList_.AddEntriesFrom(input, _repeated_baseAvatarIdList_codec);
            break;
          }
          case 64: {
            BranchId = input.ReadUInt32();
            break;
          }
          case 106:
          case 104: {
            disableAeonIdList_.AddEntriesFrom(input, _repeated_disableAeonIdList_codec);
            break;
          }
          case 114:
          case 112: {
            trialAvatarIdList_.AddEntriesFrom(input, _repeated_trialAvatarIdList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18:
          case 16: {
            startDifficultyIdList_.AddEntriesFrom(ref input, _repeated_startDifficultyIdList_codec);
            break;
          }
          case 24: {
            Id = input.ReadUInt32();
            break;
          }
          case 40: {
            AeonId = input.ReadUInt32();
            break;
          }
          case 58:
          case 56: {
            baseAvatarIdList_.AddEntriesFrom(ref input, _repeated_baseAvatarIdList_codec);
            break;
          }
          case 64: {
            BranchId = input.ReadUInt32();
            break;
          }
          case 106:
          case 104: {
            disableAeonIdList_.AddEntriesFrom(ref input, _repeated_disableAeonIdList_codec);
            break;
          }
          case 114:
          case 112: {
            trialAvatarIdList_.AddEntriesFrom(ref input, _repeated_trialAvatarIdList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
