// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CIJPOJOEGGD.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from CIJPOJOEGGD.proto</summary>
  public static partial class CIJPOJOEGGDReflection {

    #region Descriptor
    /// <summary>File descriptor for CIJPOJOEGGD.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CIJPOJOEGGDReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFDSUpQT0pPRUdHRC5wcm90byI3CgtDSUpQT0pPRUdHRBITCgtLSkJLUE9K",
            "TU9IRhgHIAEoDRITCgtDSlBPQ0tDTkZQSRgJIAEoCEIeqgIbRWdnTGluay5E",
            "YW5oZW5nU2VydmVyLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.CIJPOJOEGGD), global::EggLink.DanhengServer.Proto.CIJPOJOEGGD.Parser, new[]{ "KJBKPOJMOHF", "CJPOCKCNFPI" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CIJPOJOEGGD : pb::IMessage<CIJPOJOEGGD>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CIJPOJOEGGD> _parser = new pb::MessageParser<CIJPOJOEGGD>(() => new CIJPOJOEGGD());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CIJPOJOEGGD> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.CIJPOJOEGGDReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CIJPOJOEGGD() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CIJPOJOEGGD(CIJPOJOEGGD other) : this() {
      kJBKPOJMOHF_ = other.kJBKPOJMOHF_;
      cJPOCKCNFPI_ = other.cJPOCKCNFPI_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CIJPOJOEGGD Clone() {
      return new CIJPOJOEGGD(this);
    }

    /// <summary>Field number for the "KJBKPOJMOHF" field.</summary>
    public const int KJBKPOJMOHFFieldNumber = 7;
    private uint kJBKPOJMOHF_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint KJBKPOJMOHF {
      get { return kJBKPOJMOHF_; }
      set {
        kJBKPOJMOHF_ = value;
      }
    }

    /// <summary>Field number for the "CJPOCKCNFPI" field.</summary>
    public const int CJPOCKCNFPIFieldNumber = 9;
    private bool cJPOCKCNFPI_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool CJPOCKCNFPI {
      get { return cJPOCKCNFPI_; }
      set {
        cJPOCKCNFPI_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CIJPOJOEGGD);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CIJPOJOEGGD other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (KJBKPOJMOHF != other.KJBKPOJMOHF) return false;
      if (CJPOCKCNFPI != other.CJPOCKCNFPI) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (KJBKPOJMOHF != 0) hash ^= KJBKPOJMOHF.GetHashCode();
      if (CJPOCKCNFPI != false) hash ^= CJPOCKCNFPI.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (KJBKPOJMOHF != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(KJBKPOJMOHF);
      }
      if (CJPOCKCNFPI != false) {
        output.WriteRawTag(72);
        output.WriteBool(CJPOCKCNFPI);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (KJBKPOJMOHF != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(KJBKPOJMOHF);
      }
      if (CJPOCKCNFPI != false) {
        output.WriteRawTag(72);
        output.WriteBool(CJPOCKCNFPI);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (KJBKPOJMOHF != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(KJBKPOJMOHF);
      }
      if (CJPOCKCNFPI != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CIJPOJOEGGD other) {
      if (other == null) {
        return;
      }
      if (other.KJBKPOJMOHF != 0) {
        KJBKPOJMOHF = other.KJBKPOJMOHF;
      }
      if (other.CJPOCKCNFPI != false) {
        CJPOCKCNFPI = other.CJPOCKCNFPI;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 56: {
            KJBKPOJMOHF = input.ReadUInt32();
            break;
          }
          case 72: {
            CJPOCKCNFPI = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 56: {
            KJBKPOJMOHF = input.ReadUInt32();
            break;
          }
          case 72: {
            CJPOCKCNFPI = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
