// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CmdPlanetFesType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from CmdPlanetFesType.proto</summary>
  public static partial class CmdPlanetFesTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for CmdPlanetFesType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CmdPlanetFesTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZDbWRQbGFuZXRGZXNUeXBlLnByb3RvKt0PChBDbWRQbGFuZXRGZXNUeXBl",
            "EhgKFENtZFBsYW5ldEZlc1R5cGVOb25lEAASHQoYQ21kUGxhbmV0RmVzQnV5",
            "TGFuZENzUmVxEIxAEh0KGENtZFBsYW5ldEZlc0RvR2FjaGFTY1JzcBChQBIj",
            "Ch5DbWRQbGFuZXRGZXNHZXRBdmF0YXJTdGF0Q3NSZXEQk0ASHQoYQ21kUGxh",
            "bmV0RmVzQnV5TGFuZFNjUnNwEJ1AEiMKHkNtZFBsYW5ldEZlc0NvbGxlY3RJ",
            "bmNvbWVTY1JzcBCVQBIlCiBDbWRQbGFuZXRGZXNEZWxpdmVyUGFtQ2FyZ29T",
            "Y1JzcBCkQBIlCiBDbWRQbGFuZXRGZXNUYWtlUXVlc3RSZXdhcmRDc1JlcRCa",
            "QBItCihDbWRQbGFuZXRGZXNCdXNpbmVzc0RheVJlZnJlc2hFdmVudFNjUnNw",
            "EI5AEiIKHUNtZFBsYW5ldEZlc0NsaWVudFN0YXR1c1NjUnNwEKZAEi4KKUNt",
            "ZFBsYW5ldEZlc0dldEZyaWVuZFJhbmtpbmdJbmZvTGlzdENzUmVxELpAEh0K",
            "GENtZEdldFBsYW5ldEZlc0RhdGFDc1JlcRCJQBIjCh5DbWRQbGFuZXRGZXNT",
            "dGFydE1pbmlHYW1lU2NSc3AQtUASJwoiQ21kUGxhbmV0RmVzU2V0Q3VzdG9t",
            "S2V5VmFsdWVDc1JlcRCXQBIjCh5DbWRQbGFuZXRGZXNBdmF0YXJMZXZlbFVw",
            "Q3NSZXEQs0ASKwomQ21kUGxhbmV0RmVzVGFrZVJlZ2lvblBoYXNlUmV3YXJk",
            "U2NSc3AQuUASJQogQ21kUGxhbmV0RmVzVXBncmFkZUZlc0xldmVsU2NSc3AQ",
            "mEASLQooQ21kUGxhbmV0RmVzQ2hvb3NlQXZhdGFyRXZlbnRPcHRpb25Dc1Jl",
            "cRCyQBIlCiBDbWRQbGFuZXRGZXNEZWxpdmVyUGFtQ2FyZ29Dc1JlcRCeQBIi",
            "Ch1DbWRQbGFuZXRGZXNDbGllbnRTdGF0dXNDc1JlcRCjQBIuCilDbWRQbGFu",
            "ZXRGZXNHZXRGcmllbmRSYW5raW5nSW5mb0xpc3RTY1JzcBCLQBIjCh5DbWRQ",
            "bGFuZXRGZXNHYW1lQmluZ29GbGlwQ3NSZXEQokASJQogQ21kUGxhbmV0RmVz",
            "VGFrZVF1ZXN0UmV3YXJkU2NSc3AQt0ASLwoqQ21kUGxhbmV0RmVzRGVhbEF2",
            "YXRhckV2ZW50T3B0aW9uSXRlbUNzUmVxEJtAEigKI0NtZFBsYW5ldEZlc0dl",
            "dEJ1c2luZXNzRGF5SW5mb1NjUnNwEJlAEi0KKENtZFBsYW5ldEZlc0J1c2lu",
            "ZXNzRGF5UmVmcmVzaEV2ZW50Q3NSZXEQtkASLQooQ21kUGxhbmV0RmVzQ2hv",
            "b3NlQXZhdGFyRXZlbnRPcHRpb25TY1JzcBCrQBIoCiNDbWRQbGFuZXRGZXNC",
            "b251c0V2ZW50SW50ZXJhY3RTY1JzcBCSQBInCiJDbWRQbGFuZXRGZXNVcGdy",
            "YWRlU2tpbGxMZXZlbFNjUnNwEJBAEiMKHkNtZFBsYW5ldEZlc0F2YXRhckxl",
            "dmVsVXBTY1JzcBCRQBIjCh5DbWRQbGFuZXRGZXNHYW1lQmluZ29GbGlwU2NS",
            "c3AQqUASJwoiQ21kUGxhbmV0RmVzU2V0Q3VzdG9tS2V5VmFsdWVTY1JzcBCw",
            "QBIjCh5DbWRQbGFuZXRGZXNTeW5jQ2hhbmdlU2NOb3RpZnkQoEASJwoiQ21k",
            "UGxhbmV0RmVzVXBncmFkZVNraWxsTGV2ZWxDc1JlcRCUQBIjCh5DbWRQbGFu",
            "ZXRGZXNTdGFydE1pbmlHYW1lQ3NSZXEQikASIwoeQ21kUGxhbmV0RmVzU2V0",
            "QXZhdGFyV29ya1NjUnNwEKhAEigKI0NtZFBsYW5ldEZlc0dldEJ1c2luZXNz",
            "RGF5SW5mb0NzUmVxEJxAEh0KGENtZFBsYW5ldEZlc0RvR2FjaGFDc1JlcRCf",
            "QBIdChhDbWRHZXRQbGFuZXRGZXNEYXRhU2NSc3AQrUASHQoYQ21kUGxhbmV0",
            "RmVzVXNlSXRlbVNjUnNwEKdAEiMKHkNtZFBsYW5ldEZlc0dldEF2YXRhclN0",
            "YXRTY1JzcBCuQBIwCitDbWRQbGFuZXRGZXNGcmllbmRSYW5raW5nSW5mb0No",
            "YW5nZVNjTm90aWZ5ELRAEiMKHkNtZFBsYW5ldEZlc1NldEF2YXRhcldvcmtD",
            "c1JlcRCqQBIoCiNDbWRQbGFuZXRGZXNCb251c0V2ZW50SW50ZXJhY3RDc1Jl",
            "cRCxQBIdChhDbWRQbGFuZXRGZXNVc2VJdGVtQ3NSZXEQjUASIwoeQ21kUGxh",
            "bmV0RmVzQ29sbGVjdEluY29tZUNzUmVxEKxAEiYKIUNtZFBsYW5ldEZlc0Nv",
            "bGxlY3RBbGxJbmNvbWVTY1JzcBC4QBIrCiZDbWRQbGFuZXRGZXNUYWtlUmVn",
            "aW9uUGhhc2VSZXdhcmRDc1JlcRCPQBIvCipDbWRQbGFuZXRGZXNEZWFsQXZh",
            "dGFyRXZlbnRPcHRpb25JdGVtU2NSc3AQr0ASJQogQ21kUGxhbmV0RmVzVXBn",
            "cmFkZUZlc0xldmVsQ3NSZXEQlkASJgohQ21kUGxhbmV0RmVzQ29sbGVjdEFs",
            "bEluY29tZUNzUmVxEKVAQh6qAhtFZ2dMaW5rLkRhbmhlbmdTZXJ2ZXIuUHJv",
            "dG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::EggLink.DanhengServer.Proto.CmdPlanetFesType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum CmdPlanetFesType {
    [pbr::OriginalName("CmdPlanetFesTypeNone")] None = 0,
    [pbr::OriginalName("CmdPlanetFesBuyLandCsReq")] CmdPlanetFesBuyLandCsReq = 8204,
    [pbr::OriginalName("CmdPlanetFesDoGachaScRsp")] CmdPlanetFesDoGachaScRsp = 8225,
    [pbr::OriginalName("CmdPlanetFesGetAvatarStatCsReq")] CmdPlanetFesGetAvatarStatCsReq = 8211,
    [pbr::OriginalName("CmdPlanetFesBuyLandScRsp")] CmdPlanetFesBuyLandScRsp = 8221,
    [pbr::OriginalName("CmdPlanetFesCollectIncomeScRsp")] CmdPlanetFesCollectIncomeScRsp = 8213,
    [pbr::OriginalName("CmdPlanetFesDeliverPamCargoScRsp")] CmdPlanetFesDeliverPamCargoScRsp = 8228,
    [pbr::OriginalName("CmdPlanetFesTakeQuestRewardCsReq")] CmdPlanetFesTakeQuestRewardCsReq = 8218,
    [pbr::OriginalName("CmdPlanetFesBusinessDayRefreshEventScRsp")] CmdPlanetFesBusinessDayRefreshEventScRsp = 8206,
    [pbr::OriginalName("CmdPlanetFesClientStatusScRsp")] CmdPlanetFesClientStatusScRsp = 8230,
    [pbr::OriginalName("CmdPlanetFesGetFriendRankingInfoListCsReq")] CmdPlanetFesGetFriendRankingInfoListCsReq = 8250,
    [pbr::OriginalName("CmdGetPlanetFesDataCsReq")] CmdGetPlanetFesDataCsReq = 8201,
    [pbr::OriginalName("CmdPlanetFesStartMiniGameScRsp")] CmdPlanetFesStartMiniGameScRsp = 8245,
    [pbr::OriginalName("CmdPlanetFesSetCustomKeyValueCsReq")] CmdPlanetFesSetCustomKeyValueCsReq = 8215,
    [pbr::OriginalName("CmdPlanetFesAvatarLevelUpCsReq")] CmdPlanetFesAvatarLevelUpCsReq = 8243,
    [pbr::OriginalName("CmdPlanetFesTakeRegionPhaseRewardScRsp")] CmdPlanetFesTakeRegionPhaseRewardScRsp = 8249,
    [pbr::OriginalName("CmdPlanetFesUpgradeFesLevelScRsp")] CmdPlanetFesUpgradeFesLevelScRsp = 8216,
    [pbr::OriginalName("CmdPlanetFesChooseAvatarEventOptionCsReq")] CmdPlanetFesChooseAvatarEventOptionCsReq = 8242,
    [pbr::OriginalName("CmdPlanetFesDeliverPamCargoCsReq")] CmdPlanetFesDeliverPamCargoCsReq = 8222,
    [pbr::OriginalName("CmdPlanetFesClientStatusCsReq")] CmdPlanetFesClientStatusCsReq = 8227,
    [pbr::OriginalName("CmdPlanetFesGetFriendRankingInfoListScRsp")] CmdPlanetFesGetFriendRankingInfoListScRsp = 8203,
    [pbr::OriginalName("CmdPlanetFesGameBingoFlipCsReq")] CmdPlanetFesGameBingoFlipCsReq = 8226,
    [pbr::OriginalName("CmdPlanetFesTakeQuestRewardScRsp")] CmdPlanetFesTakeQuestRewardScRsp = 8247,
    [pbr::OriginalName("CmdPlanetFesDealAvatarEventOptionItemCsReq")] CmdPlanetFesDealAvatarEventOptionItemCsReq = 8219,
    [pbr::OriginalName("CmdPlanetFesGetBusinessDayInfoScRsp")] CmdPlanetFesGetBusinessDayInfoScRsp = 8217,
    [pbr::OriginalName("CmdPlanetFesBusinessDayRefreshEventCsReq")] CmdPlanetFesBusinessDayRefreshEventCsReq = 8246,
    [pbr::OriginalName("CmdPlanetFesChooseAvatarEventOptionScRsp")] CmdPlanetFesChooseAvatarEventOptionScRsp = 8235,
    [pbr::OriginalName("CmdPlanetFesBonusEventInteractScRsp")] CmdPlanetFesBonusEventInteractScRsp = 8210,
    [pbr::OriginalName("CmdPlanetFesUpgradeSkillLevelScRsp")] CmdPlanetFesUpgradeSkillLevelScRsp = 8208,
    [pbr::OriginalName("CmdPlanetFesAvatarLevelUpScRsp")] CmdPlanetFesAvatarLevelUpScRsp = 8209,
    [pbr::OriginalName("CmdPlanetFesGameBingoFlipScRsp")] CmdPlanetFesGameBingoFlipScRsp = 8233,
    [pbr::OriginalName("CmdPlanetFesSetCustomKeyValueScRsp")] CmdPlanetFesSetCustomKeyValueScRsp = 8240,
    [pbr::OriginalName("CmdPlanetFesSyncChangeScNotify")] CmdPlanetFesSyncChangeScNotify = 8224,
    [pbr::OriginalName("CmdPlanetFesUpgradeSkillLevelCsReq")] CmdPlanetFesUpgradeSkillLevelCsReq = 8212,
    [pbr::OriginalName("CmdPlanetFesStartMiniGameCsReq")] CmdPlanetFesStartMiniGameCsReq = 8202,
    [pbr::OriginalName("CmdPlanetFesSetAvatarWorkScRsp")] CmdPlanetFesSetAvatarWorkScRsp = 8232,
    [pbr::OriginalName("CmdPlanetFesGetBusinessDayInfoCsReq")] CmdPlanetFesGetBusinessDayInfoCsReq = 8220,
    [pbr::OriginalName("CmdPlanetFesDoGachaCsReq")] CmdPlanetFesDoGachaCsReq = 8223,
    [pbr::OriginalName("CmdGetPlanetFesDataScRsp")] CmdGetPlanetFesDataScRsp = 8237,
    [pbr::OriginalName("CmdPlanetFesUseItemScRsp")] CmdPlanetFesUseItemScRsp = 8231,
    [pbr::OriginalName("CmdPlanetFesGetAvatarStatScRsp")] CmdPlanetFesGetAvatarStatScRsp = 8238,
    [pbr::OriginalName("CmdPlanetFesFriendRankingInfoChangeScNotify")] CmdPlanetFesFriendRankingInfoChangeScNotify = 8244,
    [pbr::OriginalName("CmdPlanetFesSetAvatarWorkCsReq")] CmdPlanetFesSetAvatarWorkCsReq = 8234,
    [pbr::OriginalName("CmdPlanetFesBonusEventInteractCsReq")] CmdPlanetFesBonusEventInteractCsReq = 8241,
    [pbr::OriginalName("CmdPlanetFesUseItemCsReq")] CmdPlanetFesUseItemCsReq = 8205,
    [pbr::OriginalName("CmdPlanetFesCollectIncomeCsReq")] CmdPlanetFesCollectIncomeCsReq = 8236,
    [pbr::OriginalName("CmdPlanetFesCollectAllIncomeScRsp")] CmdPlanetFesCollectAllIncomeScRsp = 8248,
    [pbr::OriginalName("CmdPlanetFesTakeRegionPhaseRewardCsReq")] CmdPlanetFesTakeRegionPhaseRewardCsReq = 8207,
    [pbr::OriginalName("CmdPlanetFesDealAvatarEventOptionItemScRsp")] CmdPlanetFesDealAvatarEventOptionItemScRsp = 8239,
    [pbr::OriginalName("CmdPlanetFesUpgradeFesLevelCsReq")] CmdPlanetFesUpgradeFesLevelCsReq = 8214,
    [pbr::OriginalName("CmdPlanetFesCollectAllIncomeCsReq")] CmdPlanetFesCollectAllIncomeCsReq = 8229,
  }

  #endregion

}

#endregion Designer generated code
