// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: FNLGJFEOIMD.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from FNLGJFEOIMD.proto</summary>
  public static partial class FNLGJFEOIMDReflection {

    #region Descriptor
    /// <summary>File descriptor for FNLGJFEOIMD.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FNLGJFEOIMDReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFGTkxHSkZFT0lNRC5wcm90bxoSSXRlbUNvc3REYXRhLnByb3RvGg5JdGVt",
            "TGlzdC5wcm90byJ3CgtGTkxHSkZFT0lNRBITCgtCTElNRURBR1BCRhgDIAEo",
            "DRIiCgtDS0VOQ1BJSENGSBgHIAEoCzINLkl0ZW1Db3N0RGF0YRIeCgtGQ0lP",
            "S05CSkNPRhgLIAEoCzIJLkl0ZW1MaXN0Eg8KB3JldGNvZGUYDiABKA1CHqoC",
            "G0VnZ0xpbmsuRGFuaGVuZ1NlcnZlci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.ItemCostDataReflection.Descriptor, global::EggLink.DanhengServer.Proto.ItemListReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.FNLGJFEOIMD), global::EggLink.DanhengServer.Proto.FNLGJFEOIMD.Parser, new[]{ "BLIMEDAGPBF", "CKENCPIHCFH", "FCIOKNBJCOF", "Retcode" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FNLGJFEOIMD : pb::IMessage<FNLGJFEOIMD>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FNLGJFEOIMD> _parser = new pb::MessageParser<FNLGJFEOIMD>(() => new FNLGJFEOIMD());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FNLGJFEOIMD> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.FNLGJFEOIMDReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FNLGJFEOIMD() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FNLGJFEOIMD(FNLGJFEOIMD other) : this() {
      bLIMEDAGPBF_ = other.bLIMEDAGPBF_;
      cKENCPIHCFH_ = other.cKENCPIHCFH_ != null ? other.cKENCPIHCFH_.Clone() : null;
      fCIOKNBJCOF_ = other.fCIOKNBJCOF_ != null ? other.fCIOKNBJCOF_.Clone() : null;
      retcode_ = other.retcode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FNLGJFEOIMD Clone() {
      return new FNLGJFEOIMD(this);
    }

    /// <summary>Field number for the "BLIMEDAGPBF" field.</summary>
    public const int BLIMEDAGPBFFieldNumber = 3;
    private uint bLIMEDAGPBF_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BLIMEDAGPBF {
      get { return bLIMEDAGPBF_; }
      set {
        bLIMEDAGPBF_ = value;
      }
    }

    /// <summary>Field number for the "CKENCPIHCFH" field.</summary>
    public const int CKENCPIHCFHFieldNumber = 7;
    private global::EggLink.DanhengServer.Proto.ItemCostData cKENCPIHCFH_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.ItemCostData CKENCPIHCFH {
      get { return cKENCPIHCFH_; }
      set {
        cKENCPIHCFH_ = value;
      }
    }

    /// <summary>Field number for the "FCIOKNBJCOF" field.</summary>
    public const int FCIOKNBJCOFFieldNumber = 11;
    private global::EggLink.DanhengServer.Proto.ItemList fCIOKNBJCOF_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.ItemList FCIOKNBJCOF {
      get { return fCIOKNBJCOF_; }
      set {
        fCIOKNBJCOF_ = value;
      }
    }

    /// <summary>Field number for the "retcode" field.</summary>
    public const int RetcodeFieldNumber = 14;
    private uint retcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Retcode {
      get { return retcode_; }
      set {
        retcode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FNLGJFEOIMD);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FNLGJFEOIMD other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BLIMEDAGPBF != other.BLIMEDAGPBF) return false;
      if (!object.Equals(CKENCPIHCFH, other.CKENCPIHCFH)) return false;
      if (!object.Equals(FCIOKNBJCOF, other.FCIOKNBJCOF)) return false;
      if (Retcode != other.Retcode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BLIMEDAGPBF != 0) hash ^= BLIMEDAGPBF.GetHashCode();
      if (cKENCPIHCFH_ != null) hash ^= CKENCPIHCFH.GetHashCode();
      if (fCIOKNBJCOF_ != null) hash ^= FCIOKNBJCOF.GetHashCode();
      if (Retcode != 0) hash ^= Retcode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BLIMEDAGPBF != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(BLIMEDAGPBF);
      }
      if (cKENCPIHCFH_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(CKENCPIHCFH);
      }
      if (fCIOKNBJCOF_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(FCIOKNBJCOF);
      }
      if (Retcode != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(Retcode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BLIMEDAGPBF != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(BLIMEDAGPBF);
      }
      if (cKENCPIHCFH_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(CKENCPIHCFH);
      }
      if (fCIOKNBJCOF_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(FCIOKNBJCOF);
      }
      if (Retcode != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(Retcode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BLIMEDAGPBF != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BLIMEDAGPBF);
      }
      if (cKENCPIHCFH_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CKENCPIHCFH);
      }
      if (fCIOKNBJCOF_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FCIOKNBJCOF);
      }
      if (Retcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Retcode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FNLGJFEOIMD other) {
      if (other == null) {
        return;
      }
      if (other.BLIMEDAGPBF != 0) {
        BLIMEDAGPBF = other.BLIMEDAGPBF;
      }
      if (other.cKENCPIHCFH_ != null) {
        if (cKENCPIHCFH_ == null) {
          CKENCPIHCFH = new global::EggLink.DanhengServer.Proto.ItemCostData();
        }
        CKENCPIHCFH.MergeFrom(other.CKENCPIHCFH);
      }
      if (other.fCIOKNBJCOF_ != null) {
        if (fCIOKNBJCOF_ == null) {
          FCIOKNBJCOF = new global::EggLink.DanhengServer.Proto.ItemList();
        }
        FCIOKNBJCOF.MergeFrom(other.FCIOKNBJCOF);
      }
      if (other.Retcode != 0) {
        Retcode = other.Retcode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 24: {
            BLIMEDAGPBF = input.ReadUInt32();
            break;
          }
          case 58: {
            if (cKENCPIHCFH_ == null) {
              CKENCPIHCFH = new global::EggLink.DanhengServer.Proto.ItemCostData();
            }
            input.ReadMessage(CKENCPIHCFH);
            break;
          }
          case 90: {
            if (fCIOKNBJCOF_ == null) {
              FCIOKNBJCOF = new global::EggLink.DanhengServer.Proto.ItemList();
            }
            input.ReadMessage(FCIOKNBJCOF);
            break;
          }
          case 112: {
            Retcode = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 24: {
            BLIMEDAGPBF = input.ReadUInt32();
            break;
          }
          case 58: {
            if (cKENCPIHCFH_ == null) {
              CKENCPIHCFH = new global::EggLink.DanhengServer.Proto.ItemCostData();
            }
            input.ReadMessage(CKENCPIHCFH);
            break;
          }
          case 90: {
            if (fCIOKNBJCOF_ == null) {
              FCIOKNBJCOF = new global::EggLink.DanhengServer.Proto.ItemList();
            }
            input.ReadMessage(FCIOKNBJCOF);
            break;
          }
          case 112: {
            Retcode = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
