// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GGOKNMBKMNA.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from GGOKNMBKMNA.proto</summary>
  public static partial class GGOKNMBKMNAReflection {

    #region Descriptor
    /// <summary>File descriptor for GGOKNMBKMNA.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GGOKNMBKMNAReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFHR09LTk1CS01OQS5wcm90bxoRTU5NTENGUENMTUkucHJvdG8iggIKC0dH",
            "T0tOTUJLTU5BEhMKC09FUEVCSE5OUE5PGAEgASgNEhMKC0pFT0NBUEFPR0FH",
            "GAIgASgNEhMKC0RKT0JFSUFJUExGGAMgASgNEhMKC0xBTEZJSUJDREVNGAQg",
            "ASgNEiEKC0JCSk9PTk1KSERIGAUgAygLMgwuTU5NTENGUENMTUkSEwoLSkdK",
            "UERORk5FSEYYBiABKA0SEwoLSVBKSEpHT0dETkMYByABKA0SEwoLRUtGR0lC",
            "SUpFTkIYCiABKA0SEwoLSkFCUEJQTFBPTUMYCyABKA0SEwoLTEVBTUVITEdJ",
            "Q0YYDCABKA0SEwoLQVBPR05LT0hLRE4YDSABKA1CHqoCG0VnZ0xpbmsuRGFu",
            "aGVuZ1NlcnZlci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.MNMLCFPCLMIReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.GGOKNMBKMNA), global::EggLink.DanhengServer.Proto.GGOKNMBKMNA.Parser, new[]{ "OEPEBHNNPNO", "JEOCAPAOGAG", "DJOBEIAIPLF", "LALFIIBCDEM", "BBJOONMJHDH", "JGJPDNFNEHF", "IPJHJGOGDNC", "EKFGIBIJENB", "JABPBPLPOMC", "LEAMEHLGICF", "APOGNKOHKDN" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GGOKNMBKMNA : pb::IMessage<GGOKNMBKMNA>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GGOKNMBKMNA> _parser = new pb::MessageParser<GGOKNMBKMNA>(() => new GGOKNMBKMNA());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GGOKNMBKMNA> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.GGOKNMBKMNAReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GGOKNMBKMNA() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GGOKNMBKMNA(GGOKNMBKMNA other) : this() {
      oEPEBHNNPNO_ = other.oEPEBHNNPNO_;
      jEOCAPAOGAG_ = other.jEOCAPAOGAG_;
      dJOBEIAIPLF_ = other.dJOBEIAIPLF_;
      lALFIIBCDEM_ = other.lALFIIBCDEM_;
      bBJOONMJHDH_ = other.bBJOONMJHDH_.Clone();
      jGJPDNFNEHF_ = other.jGJPDNFNEHF_;
      iPJHJGOGDNC_ = other.iPJHJGOGDNC_;
      eKFGIBIJENB_ = other.eKFGIBIJENB_;
      jABPBPLPOMC_ = other.jABPBPLPOMC_;
      lEAMEHLGICF_ = other.lEAMEHLGICF_;
      aPOGNKOHKDN_ = other.aPOGNKOHKDN_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GGOKNMBKMNA Clone() {
      return new GGOKNMBKMNA(this);
    }

    /// <summary>Field number for the "OEPEBHNNPNO" field.</summary>
    public const int OEPEBHNNPNOFieldNumber = 1;
    private uint oEPEBHNNPNO_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint OEPEBHNNPNO {
      get { return oEPEBHNNPNO_; }
      set {
        oEPEBHNNPNO_ = value;
      }
    }

    /// <summary>Field number for the "JEOCAPAOGAG" field.</summary>
    public const int JEOCAPAOGAGFieldNumber = 2;
    private uint jEOCAPAOGAG_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint JEOCAPAOGAG {
      get { return jEOCAPAOGAG_; }
      set {
        jEOCAPAOGAG_ = value;
      }
    }

    /// <summary>Field number for the "DJOBEIAIPLF" field.</summary>
    public const int DJOBEIAIPLFFieldNumber = 3;
    private uint dJOBEIAIPLF_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DJOBEIAIPLF {
      get { return dJOBEIAIPLF_; }
      set {
        dJOBEIAIPLF_ = value;
      }
    }

    /// <summary>Field number for the "LALFIIBCDEM" field.</summary>
    public const int LALFIIBCDEMFieldNumber = 4;
    private uint lALFIIBCDEM_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LALFIIBCDEM {
      get { return lALFIIBCDEM_; }
      set {
        lALFIIBCDEM_ = value;
      }
    }

    /// <summary>Field number for the "BBJOONMJHDH" field.</summary>
    public const int BBJOONMJHDHFieldNumber = 5;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.MNMLCFPCLMI> _repeated_bBJOONMJHDH_codec
        = pb::FieldCodec.ForMessage(42, global::EggLink.DanhengServer.Proto.MNMLCFPCLMI.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.MNMLCFPCLMI> bBJOONMJHDH_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.MNMLCFPCLMI>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.MNMLCFPCLMI> BBJOONMJHDH {
      get { return bBJOONMJHDH_; }
    }

    /// <summary>Field number for the "JGJPDNFNEHF" field.</summary>
    public const int JGJPDNFNEHFFieldNumber = 6;
    private uint jGJPDNFNEHF_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint JGJPDNFNEHF {
      get { return jGJPDNFNEHF_; }
      set {
        jGJPDNFNEHF_ = value;
      }
    }

    /// <summary>Field number for the "IPJHJGOGDNC" field.</summary>
    public const int IPJHJGOGDNCFieldNumber = 7;
    private uint iPJHJGOGDNC_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint IPJHJGOGDNC {
      get { return iPJHJGOGDNC_; }
      set {
        iPJHJGOGDNC_ = value;
      }
    }

    /// <summary>Field number for the "EKFGIBIJENB" field.</summary>
    public const int EKFGIBIJENBFieldNumber = 10;
    private uint eKFGIBIJENB_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EKFGIBIJENB {
      get { return eKFGIBIJENB_; }
      set {
        eKFGIBIJENB_ = value;
      }
    }

    /// <summary>Field number for the "JABPBPLPOMC" field.</summary>
    public const int JABPBPLPOMCFieldNumber = 11;
    private uint jABPBPLPOMC_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint JABPBPLPOMC {
      get { return jABPBPLPOMC_; }
      set {
        jABPBPLPOMC_ = value;
      }
    }

    /// <summary>Field number for the "LEAMEHLGICF" field.</summary>
    public const int LEAMEHLGICFFieldNumber = 12;
    private uint lEAMEHLGICF_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LEAMEHLGICF {
      get { return lEAMEHLGICF_; }
      set {
        lEAMEHLGICF_ = value;
      }
    }

    /// <summary>Field number for the "APOGNKOHKDN" field.</summary>
    public const int APOGNKOHKDNFieldNumber = 13;
    private uint aPOGNKOHKDN_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint APOGNKOHKDN {
      get { return aPOGNKOHKDN_; }
      set {
        aPOGNKOHKDN_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GGOKNMBKMNA);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GGOKNMBKMNA other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OEPEBHNNPNO != other.OEPEBHNNPNO) return false;
      if (JEOCAPAOGAG != other.JEOCAPAOGAG) return false;
      if (DJOBEIAIPLF != other.DJOBEIAIPLF) return false;
      if (LALFIIBCDEM != other.LALFIIBCDEM) return false;
      if(!bBJOONMJHDH_.Equals(other.bBJOONMJHDH_)) return false;
      if (JGJPDNFNEHF != other.JGJPDNFNEHF) return false;
      if (IPJHJGOGDNC != other.IPJHJGOGDNC) return false;
      if (EKFGIBIJENB != other.EKFGIBIJENB) return false;
      if (JABPBPLPOMC != other.JABPBPLPOMC) return false;
      if (LEAMEHLGICF != other.LEAMEHLGICF) return false;
      if (APOGNKOHKDN != other.APOGNKOHKDN) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (OEPEBHNNPNO != 0) hash ^= OEPEBHNNPNO.GetHashCode();
      if (JEOCAPAOGAG != 0) hash ^= JEOCAPAOGAG.GetHashCode();
      if (DJOBEIAIPLF != 0) hash ^= DJOBEIAIPLF.GetHashCode();
      if (LALFIIBCDEM != 0) hash ^= LALFIIBCDEM.GetHashCode();
      hash ^= bBJOONMJHDH_.GetHashCode();
      if (JGJPDNFNEHF != 0) hash ^= JGJPDNFNEHF.GetHashCode();
      if (IPJHJGOGDNC != 0) hash ^= IPJHJGOGDNC.GetHashCode();
      if (EKFGIBIJENB != 0) hash ^= EKFGIBIJENB.GetHashCode();
      if (JABPBPLPOMC != 0) hash ^= JABPBPLPOMC.GetHashCode();
      if (LEAMEHLGICF != 0) hash ^= LEAMEHLGICF.GetHashCode();
      if (APOGNKOHKDN != 0) hash ^= APOGNKOHKDN.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (OEPEBHNNPNO != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(OEPEBHNNPNO);
      }
      if (JEOCAPAOGAG != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(JEOCAPAOGAG);
      }
      if (DJOBEIAIPLF != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(DJOBEIAIPLF);
      }
      if (LALFIIBCDEM != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(LALFIIBCDEM);
      }
      bBJOONMJHDH_.WriteTo(output, _repeated_bBJOONMJHDH_codec);
      if (JGJPDNFNEHF != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(JGJPDNFNEHF);
      }
      if (IPJHJGOGDNC != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(IPJHJGOGDNC);
      }
      if (EKFGIBIJENB != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(EKFGIBIJENB);
      }
      if (JABPBPLPOMC != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(JABPBPLPOMC);
      }
      if (LEAMEHLGICF != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(LEAMEHLGICF);
      }
      if (APOGNKOHKDN != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(APOGNKOHKDN);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (OEPEBHNNPNO != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(OEPEBHNNPNO);
      }
      if (JEOCAPAOGAG != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(JEOCAPAOGAG);
      }
      if (DJOBEIAIPLF != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(DJOBEIAIPLF);
      }
      if (LALFIIBCDEM != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(LALFIIBCDEM);
      }
      bBJOONMJHDH_.WriteTo(ref output, _repeated_bBJOONMJHDH_codec);
      if (JGJPDNFNEHF != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(JGJPDNFNEHF);
      }
      if (IPJHJGOGDNC != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(IPJHJGOGDNC);
      }
      if (EKFGIBIJENB != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(EKFGIBIJENB);
      }
      if (JABPBPLPOMC != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(JABPBPLPOMC);
      }
      if (LEAMEHLGICF != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(LEAMEHLGICF);
      }
      if (APOGNKOHKDN != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(APOGNKOHKDN);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (OEPEBHNNPNO != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(OEPEBHNNPNO);
      }
      if (JEOCAPAOGAG != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(JEOCAPAOGAG);
      }
      if (DJOBEIAIPLF != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DJOBEIAIPLF);
      }
      if (LALFIIBCDEM != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LALFIIBCDEM);
      }
      size += bBJOONMJHDH_.CalculateSize(_repeated_bBJOONMJHDH_codec);
      if (JGJPDNFNEHF != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(JGJPDNFNEHF);
      }
      if (IPJHJGOGDNC != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(IPJHJGOGDNC);
      }
      if (EKFGIBIJENB != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EKFGIBIJENB);
      }
      if (JABPBPLPOMC != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(JABPBPLPOMC);
      }
      if (LEAMEHLGICF != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LEAMEHLGICF);
      }
      if (APOGNKOHKDN != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(APOGNKOHKDN);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GGOKNMBKMNA other) {
      if (other == null) {
        return;
      }
      if (other.OEPEBHNNPNO != 0) {
        OEPEBHNNPNO = other.OEPEBHNNPNO;
      }
      if (other.JEOCAPAOGAG != 0) {
        JEOCAPAOGAG = other.JEOCAPAOGAG;
      }
      if (other.DJOBEIAIPLF != 0) {
        DJOBEIAIPLF = other.DJOBEIAIPLF;
      }
      if (other.LALFIIBCDEM != 0) {
        LALFIIBCDEM = other.LALFIIBCDEM;
      }
      bBJOONMJHDH_.Add(other.bBJOONMJHDH_);
      if (other.JGJPDNFNEHF != 0) {
        JGJPDNFNEHF = other.JGJPDNFNEHF;
      }
      if (other.IPJHJGOGDNC != 0) {
        IPJHJGOGDNC = other.IPJHJGOGDNC;
      }
      if (other.EKFGIBIJENB != 0) {
        EKFGIBIJENB = other.EKFGIBIJENB;
      }
      if (other.JABPBPLPOMC != 0) {
        JABPBPLPOMC = other.JABPBPLPOMC;
      }
      if (other.LEAMEHLGICF != 0) {
        LEAMEHLGICF = other.LEAMEHLGICF;
      }
      if (other.APOGNKOHKDN != 0) {
        APOGNKOHKDN = other.APOGNKOHKDN;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            OEPEBHNNPNO = input.ReadUInt32();
            break;
          }
          case 16: {
            JEOCAPAOGAG = input.ReadUInt32();
            break;
          }
          case 24: {
            DJOBEIAIPLF = input.ReadUInt32();
            break;
          }
          case 32: {
            LALFIIBCDEM = input.ReadUInt32();
            break;
          }
          case 42: {
            bBJOONMJHDH_.AddEntriesFrom(input, _repeated_bBJOONMJHDH_codec);
            break;
          }
          case 48: {
            JGJPDNFNEHF = input.ReadUInt32();
            break;
          }
          case 56: {
            IPJHJGOGDNC = input.ReadUInt32();
            break;
          }
          case 80: {
            EKFGIBIJENB = input.ReadUInt32();
            break;
          }
          case 88: {
            JABPBPLPOMC = input.ReadUInt32();
            break;
          }
          case 96: {
            LEAMEHLGICF = input.ReadUInt32();
            break;
          }
          case 104: {
            APOGNKOHKDN = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            OEPEBHNNPNO = input.ReadUInt32();
            break;
          }
          case 16: {
            JEOCAPAOGAG = input.ReadUInt32();
            break;
          }
          case 24: {
            DJOBEIAIPLF = input.ReadUInt32();
            break;
          }
          case 32: {
            LALFIIBCDEM = input.ReadUInt32();
            break;
          }
          case 42: {
            bBJOONMJHDH_.AddEntriesFrom(ref input, _repeated_bBJOONMJHDH_codec);
            break;
          }
          case 48: {
            JGJPDNFNEHF = input.ReadUInt32();
            break;
          }
          case 56: {
            IPJHJGOGDNC = input.ReadUInt32();
            break;
          }
          case 80: {
            EKFGIBIJENB = input.ReadUInt32();
            break;
          }
          case 88: {
            JABPBPLPOMC = input.ReadUInt32();
            break;
          }
          case 96: {
            LEAMEHLGICF = input.ReadUInt32();
            break;
          }
          case 104: {
            APOGNKOHKDN = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
