// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: HDFNBAECDLI.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from HDFNBAECDLI.proto</summary>
  public static partial class HDFNBAECDLIReflection {

    #region Descriptor
    /// <summary>File descriptor for HDFNBAECDLI.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HDFNBAECDLIReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFIREZOQkFFQ0RMSS5wcm90bxoRQUhLTU5QSEVBQ0cucHJvdG8aHlB1bmtM",
            "b3JkTW9uc3RlckJhc2ljSW5mby5wcm90bxolUHVua0xvcmRNb25zdGVySW5m",
            "b05vdGlmeVJlYXNvbi5wcm90byKmAQoLSERGTkJBRUNETEkSEwoLSkFCRkdJ",
            "S0JIT08YBiADKA0SIQoLTUZQR0xHUElQSVAYCiABKAsyDC5BSEtNTlBIRUFD",
            "RxItCgpiYXNpY19pbmZvGAwgASgLMhkuUHVua0xvcmRNb25zdGVyQmFzaWNJ",
            "bmZvEjAKBnJlYXNvbhgNIAEoDjIgLlB1bmtMb3JkTW9uc3RlckluZm9Ob3Rp",
            "ZnlSZWFzb25CHqoCG0VnZ0xpbmsuRGFuaGVuZ1NlcnZlci5Qcm90b2IGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.AHKMNPHEACGReflection.Descriptor, global::EggLink.DanhengServer.Proto.PunkLordMonsterBasicInfoReflection.Descriptor, global::EggLink.DanhengServer.Proto.PunkLordMonsterInfoNotifyReasonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.HDFNBAECDLI), global::EggLink.DanhengServer.Proto.HDFNBAECDLI.Parser, new[]{ "JABFGIKBHOO", "MFPGLGPIPIP", "BasicInfo", "Reason" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HDFNBAECDLI : pb::IMessage<HDFNBAECDLI>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HDFNBAECDLI> _parser = new pb::MessageParser<HDFNBAECDLI>(() => new HDFNBAECDLI());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HDFNBAECDLI> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.HDFNBAECDLIReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HDFNBAECDLI() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HDFNBAECDLI(HDFNBAECDLI other) : this() {
      jABFGIKBHOO_ = other.jABFGIKBHOO_.Clone();
      mFPGLGPIPIP_ = other.mFPGLGPIPIP_ != null ? other.mFPGLGPIPIP_.Clone() : null;
      basicInfo_ = other.basicInfo_ != null ? other.basicInfo_.Clone() : null;
      reason_ = other.reason_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HDFNBAECDLI Clone() {
      return new HDFNBAECDLI(this);
    }

    /// <summary>Field number for the "JABFGIKBHOO" field.</summary>
    public const int JABFGIKBHOOFieldNumber = 6;
    private static readonly pb::FieldCodec<uint> _repeated_jABFGIKBHOO_codec
        = pb::FieldCodec.ForUInt32(50);
    private readonly pbc::RepeatedField<uint> jABFGIKBHOO_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> JABFGIKBHOO {
      get { return jABFGIKBHOO_; }
    }

    /// <summary>Field number for the "MFPGLGPIPIP" field.</summary>
    public const int MFPGLGPIPIPFieldNumber = 10;
    private global::EggLink.DanhengServer.Proto.AHKMNPHEACG mFPGLGPIPIP_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.AHKMNPHEACG MFPGLGPIPIP {
      get { return mFPGLGPIPIP_; }
      set {
        mFPGLGPIPIP_ = value;
      }
    }

    /// <summary>Field number for the "basic_info" field.</summary>
    public const int BasicInfoFieldNumber = 12;
    private global::EggLink.DanhengServer.Proto.PunkLordMonsterBasicInfo basicInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.PunkLordMonsterBasicInfo BasicInfo {
      get { return basicInfo_; }
      set {
        basicInfo_ = value;
      }
    }

    /// <summary>Field number for the "reason" field.</summary>
    public const int ReasonFieldNumber = 13;
    private global::EggLink.DanhengServer.Proto.PunkLordMonsterInfoNotifyReason reason_ = global::EggLink.DanhengServer.Proto.PunkLordMonsterInfoNotifyReason.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.PunkLordMonsterInfoNotifyReason Reason {
      get { return reason_; }
      set {
        reason_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HDFNBAECDLI);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HDFNBAECDLI other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!jABFGIKBHOO_.Equals(other.jABFGIKBHOO_)) return false;
      if (!object.Equals(MFPGLGPIPIP, other.MFPGLGPIPIP)) return false;
      if (!object.Equals(BasicInfo, other.BasicInfo)) return false;
      if (Reason != other.Reason) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= jABFGIKBHOO_.GetHashCode();
      if (mFPGLGPIPIP_ != null) hash ^= MFPGLGPIPIP.GetHashCode();
      if (basicInfo_ != null) hash ^= BasicInfo.GetHashCode();
      if (Reason != global::EggLink.DanhengServer.Proto.PunkLordMonsterInfoNotifyReason.None) hash ^= Reason.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      jABFGIKBHOO_.WriteTo(output, _repeated_jABFGIKBHOO_codec);
      if (mFPGLGPIPIP_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(MFPGLGPIPIP);
      }
      if (basicInfo_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(BasicInfo);
      }
      if (Reason != global::EggLink.DanhengServer.Proto.PunkLordMonsterInfoNotifyReason.None) {
        output.WriteRawTag(104);
        output.WriteEnum((int) Reason);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      jABFGIKBHOO_.WriteTo(ref output, _repeated_jABFGIKBHOO_codec);
      if (mFPGLGPIPIP_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(MFPGLGPIPIP);
      }
      if (basicInfo_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(BasicInfo);
      }
      if (Reason != global::EggLink.DanhengServer.Proto.PunkLordMonsterInfoNotifyReason.None) {
        output.WriteRawTag(104);
        output.WriteEnum((int) Reason);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += jABFGIKBHOO_.CalculateSize(_repeated_jABFGIKBHOO_codec);
      if (mFPGLGPIPIP_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MFPGLGPIPIP);
      }
      if (basicInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BasicInfo);
      }
      if (Reason != global::EggLink.DanhengServer.Proto.PunkLordMonsterInfoNotifyReason.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Reason);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HDFNBAECDLI other) {
      if (other == null) {
        return;
      }
      jABFGIKBHOO_.Add(other.jABFGIKBHOO_);
      if (other.mFPGLGPIPIP_ != null) {
        if (mFPGLGPIPIP_ == null) {
          MFPGLGPIPIP = new global::EggLink.DanhengServer.Proto.AHKMNPHEACG();
        }
        MFPGLGPIPIP.MergeFrom(other.MFPGLGPIPIP);
      }
      if (other.basicInfo_ != null) {
        if (basicInfo_ == null) {
          BasicInfo = new global::EggLink.DanhengServer.Proto.PunkLordMonsterBasicInfo();
        }
        BasicInfo.MergeFrom(other.BasicInfo);
      }
      if (other.Reason != global::EggLink.DanhengServer.Proto.PunkLordMonsterInfoNotifyReason.None) {
        Reason = other.Reason;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 50:
          case 48: {
            jABFGIKBHOO_.AddEntriesFrom(input, _repeated_jABFGIKBHOO_codec);
            break;
          }
          case 82: {
            if (mFPGLGPIPIP_ == null) {
              MFPGLGPIPIP = new global::EggLink.DanhengServer.Proto.AHKMNPHEACG();
            }
            input.ReadMessage(MFPGLGPIPIP);
            break;
          }
          case 98: {
            if (basicInfo_ == null) {
              BasicInfo = new global::EggLink.DanhengServer.Proto.PunkLordMonsterBasicInfo();
            }
            input.ReadMessage(BasicInfo);
            break;
          }
          case 104: {
            Reason = (global::EggLink.DanhengServer.Proto.PunkLordMonsterInfoNotifyReason) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 50:
          case 48: {
            jABFGIKBHOO_.AddEntriesFrom(ref input, _repeated_jABFGIKBHOO_codec);
            break;
          }
          case 82: {
            if (mFPGLGPIPIP_ == null) {
              MFPGLGPIPIP = new global::EggLink.DanhengServer.Proto.AHKMNPHEACG();
            }
            input.ReadMessage(MFPGLGPIPIP);
            break;
          }
          case 98: {
            if (basicInfo_ == null) {
              BasicInfo = new global::EggLink.DanhengServer.Proto.PunkLordMonsterBasicInfo();
            }
            input.ReadMessage(BasicInfo);
            break;
          }
          case 104: {
            Reason = (global::EggLink.DanhengServer.Proto.PunkLordMonsterInfoNotifyReason) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
