// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: IMKLJONLOOI.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from IMKLJONLOOI.proto</summary>
  public static partial class IMKLJONLOOIReflection {

    #region Descriptor
    /// <summary>File descriptor for IMKLJONLOOI.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static IMKLJONLOOIReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFJTUtMSk9OTE9PSS5wcm90byKhAQoLSU1LTEpPTkxPT0kSDgoGYXR0YWNr",
            "GAEgASgFEhMKC0tKUE9KREpHTEpOGAIgASgNEhMKC0lHQlBDSUJMTkJIGAcg",
            "ASgNEg0KBWluZGV4GAkgASgNEhMKC0dIS0tKS0VCRUpHGAsgASgNEhMKC1BN",
            "R0JPRkdDSUpLGAwgASgNEhMKC0ZDQUFCQUtFTEdLGA0gASgNEgoKAmhwGA4g",
            "ASgFQh6qAhtFZ2dMaW5rLkRhbmhlbmdTZXJ2ZXIuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.IMKLJONLOOI), global::EggLink.DanhengServer.Proto.IMKLJONLOOI.Parser, new[]{ "Attack", "KJPOJDJGLJN", "IGBPCIBLNBH", "Index", "GHKKJKEBEJG", "PMGBOFGCIJK", "FCAABAKELGK", "Hp" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class IMKLJONLOOI : pb::IMessage<IMKLJONLOOI>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<IMKLJONLOOI> _parser = new pb::MessageParser<IMKLJONLOOI>(() => new IMKLJONLOOI());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<IMKLJONLOOI> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.IMKLJONLOOIReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IMKLJONLOOI() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IMKLJONLOOI(IMKLJONLOOI other) : this() {
      attack_ = other.attack_;
      kJPOJDJGLJN_ = other.kJPOJDJGLJN_;
      iGBPCIBLNBH_ = other.iGBPCIBLNBH_;
      index_ = other.index_;
      gHKKJKEBEJG_ = other.gHKKJKEBEJG_;
      pMGBOFGCIJK_ = other.pMGBOFGCIJK_;
      fCAABAKELGK_ = other.fCAABAKELGK_;
      hp_ = other.hp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IMKLJONLOOI Clone() {
      return new IMKLJONLOOI(this);
    }

    /// <summary>Field number for the "attack" field.</summary>
    public const int AttackFieldNumber = 1;
    private int attack_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Attack {
      get { return attack_; }
      set {
        attack_ = value;
      }
    }

    /// <summary>Field number for the "KJPOJDJGLJN" field.</summary>
    public const int KJPOJDJGLJNFieldNumber = 2;
    private uint kJPOJDJGLJN_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint KJPOJDJGLJN {
      get { return kJPOJDJGLJN_; }
      set {
        kJPOJDJGLJN_ = value;
      }
    }

    /// <summary>Field number for the "IGBPCIBLNBH" field.</summary>
    public const int IGBPCIBLNBHFieldNumber = 7;
    private uint iGBPCIBLNBH_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint IGBPCIBLNBH {
      get { return iGBPCIBLNBH_; }
      set {
        iGBPCIBLNBH_ = value;
      }
    }

    /// <summary>Field number for the "index" field.</summary>
    public const int IndexFieldNumber = 9;
    private uint index_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Index {
      get { return index_; }
      set {
        index_ = value;
      }
    }

    /// <summary>Field number for the "GHKKJKEBEJG" field.</summary>
    public const int GHKKJKEBEJGFieldNumber = 11;
    private uint gHKKJKEBEJG_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GHKKJKEBEJG {
      get { return gHKKJKEBEJG_; }
      set {
        gHKKJKEBEJG_ = value;
      }
    }

    /// <summary>Field number for the "PMGBOFGCIJK" field.</summary>
    public const int PMGBOFGCIJKFieldNumber = 12;
    private uint pMGBOFGCIJK_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PMGBOFGCIJK {
      get { return pMGBOFGCIJK_; }
      set {
        pMGBOFGCIJK_ = value;
      }
    }

    /// <summary>Field number for the "FCAABAKELGK" field.</summary>
    public const int FCAABAKELGKFieldNumber = 13;
    private uint fCAABAKELGK_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FCAABAKELGK {
      get { return fCAABAKELGK_; }
      set {
        fCAABAKELGK_ = value;
      }
    }

    /// <summary>Field number for the "hp" field.</summary>
    public const int HpFieldNumber = 14;
    private int hp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Hp {
      get { return hp_; }
      set {
        hp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as IMKLJONLOOI);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(IMKLJONLOOI other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Attack != other.Attack) return false;
      if (KJPOJDJGLJN != other.KJPOJDJGLJN) return false;
      if (IGBPCIBLNBH != other.IGBPCIBLNBH) return false;
      if (Index != other.Index) return false;
      if (GHKKJKEBEJG != other.GHKKJKEBEJG) return false;
      if (PMGBOFGCIJK != other.PMGBOFGCIJK) return false;
      if (FCAABAKELGK != other.FCAABAKELGK) return false;
      if (Hp != other.Hp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Attack != 0) hash ^= Attack.GetHashCode();
      if (KJPOJDJGLJN != 0) hash ^= KJPOJDJGLJN.GetHashCode();
      if (IGBPCIBLNBH != 0) hash ^= IGBPCIBLNBH.GetHashCode();
      if (Index != 0) hash ^= Index.GetHashCode();
      if (GHKKJKEBEJG != 0) hash ^= GHKKJKEBEJG.GetHashCode();
      if (PMGBOFGCIJK != 0) hash ^= PMGBOFGCIJK.GetHashCode();
      if (FCAABAKELGK != 0) hash ^= FCAABAKELGK.GetHashCode();
      if (Hp != 0) hash ^= Hp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Attack != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Attack);
      }
      if (KJPOJDJGLJN != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(KJPOJDJGLJN);
      }
      if (IGBPCIBLNBH != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(IGBPCIBLNBH);
      }
      if (Index != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(Index);
      }
      if (GHKKJKEBEJG != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(GHKKJKEBEJG);
      }
      if (PMGBOFGCIJK != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(PMGBOFGCIJK);
      }
      if (FCAABAKELGK != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(FCAABAKELGK);
      }
      if (Hp != 0) {
        output.WriteRawTag(112);
        output.WriteInt32(Hp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Attack != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Attack);
      }
      if (KJPOJDJGLJN != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(KJPOJDJGLJN);
      }
      if (IGBPCIBLNBH != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(IGBPCIBLNBH);
      }
      if (Index != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(Index);
      }
      if (GHKKJKEBEJG != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(GHKKJKEBEJG);
      }
      if (PMGBOFGCIJK != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(PMGBOFGCIJK);
      }
      if (FCAABAKELGK != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(FCAABAKELGK);
      }
      if (Hp != 0) {
        output.WriteRawTag(112);
        output.WriteInt32(Hp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Attack != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Attack);
      }
      if (KJPOJDJGLJN != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(KJPOJDJGLJN);
      }
      if (IGBPCIBLNBH != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(IGBPCIBLNBH);
      }
      if (Index != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Index);
      }
      if (GHKKJKEBEJG != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GHKKJKEBEJG);
      }
      if (PMGBOFGCIJK != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PMGBOFGCIJK);
      }
      if (FCAABAKELGK != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FCAABAKELGK);
      }
      if (Hp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Hp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(IMKLJONLOOI other) {
      if (other == null) {
        return;
      }
      if (other.Attack != 0) {
        Attack = other.Attack;
      }
      if (other.KJPOJDJGLJN != 0) {
        KJPOJDJGLJN = other.KJPOJDJGLJN;
      }
      if (other.IGBPCIBLNBH != 0) {
        IGBPCIBLNBH = other.IGBPCIBLNBH;
      }
      if (other.Index != 0) {
        Index = other.Index;
      }
      if (other.GHKKJKEBEJG != 0) {
        GHKKJKEBEJG = other.GHKKJKEBEJG;
      }
      if (other.PMGBOFGCIJK != 0) {
        PMGBOFGCIJK = other.PMGBOFGCIJK;
      }
      if (other.FCAABAKELGK != 0) {
        FCAABAKELGK = other.FCAABAKELGK;
      }
      if (other.Hp != 0) {
        Hp = other.Hp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Attack = input.ReadInt32();
            break;
          }
          case 16: {
            KJPOJDJGLJN = input.ReadUInt32();
            break;
          }
          case 56: {
            IGBPCIBLNBH = input.ReadUInt32();
            break;
          }
          case 72: {
            Index = input.ReadUInt32();
            break;
          }
          case 88: {
            GHKKJKEBEJG = input.ReadUInt32();
            break;
          }
          case 96: {
            PMGBOFGCIJK = input.ReadUInt32();
            break;
          }
          case 104: {
            FCAABAKELGK = input.ReadUInt32();
            break;
          }
          case 112: {
            Hp = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Attack = input.ReadInt32();
            break;
          }
          case 16: {
            KJPOJDJGLJN = input.ReadUInt32();
            break;
          }
          case 56: {
            IGBPCIBLNBH = input.ReadUInt32();
            break;
          }
          case 72: {
            Index = input.ReadUInt32();
            break;
          }
          case 88: {
            GHKKJKEBEJG = input.ReadUInt32();
            break;
          }
          case 96: {
            PMGBOFGCIJK = input.ReadUInt32();
            break;
          }
          case 104: {
            FCAABAKELGK = input.ReadUInt32();
            break;
          }
          case 112: {
            Hp = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
