// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: JGPPDJHFIEK.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from JGPPDJHFIEK.proto</summary>
  public static partial class JGPPDJHFIEKReflection {

    #region Descriptor
    /// <summary>File descriptor for JGPPDJHFIEK.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static JGPPDJHFIEKReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFKR1BQREpIRklFSy5wcm90byq7AQoLSkdQUERKSEZJRUsSGwoXSkdQUERK",
            "SEZJRUtfSUZCRFBDRE1CR00QABIbChdKR1BQREpIRklFS19HTUpFS0dFQUxN",
            "RRABEhsKF0pHUFBESkhGSUVLX0ZIQ0dKRklQTUJQEAISGwoXSkdQUERKSEZJ",
            "RUtfSE1OTktDR0pJSEUQAxIbChdKR1BQREpIRklFS19PS1BCRENDSEFFThAE",
            "EhsKF0pHUFBESkhGSUVLX0VQR0NOUEVCQ0xGEAVCHqoCG0VnZ0xpbmsuRGFu",
            "aGVuZ1NlcnZlci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::EggLink.DanhengServer.Proto.JGPPDJHFIEK), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum JGPPDJHFIEK {
    [pbr::OriginalName("JGPPDJHFIEK_IFBDPCDMBGM")] Ifbdpcdmbgm = 0,
    [pbr::OriginalName("JGPPDJHFIEK_GMJEKGEALME")] Gmjekgealme = 1,
    [pbr::OriginalName("JGPPDJHFIEK_FHCGJFIPMBP")] Fhcgjfipmbp = 2,
    [pbr::OriginalName("JGPPDJHFIEK_HMNNKCGJIHE")] Hmnnkcgjihe = 3,
    [pbr::OriginalName("JGPPDJHFIEK_OKPBDCCHAEN")] Okpbdcchaen = 4,
    [pbr::OriginalName("JGPPDJHFIEK_EPGCNPEBCLF")] Epgcnpebclf = 5,
  }

  #endregion

}

#endregion Designer generated code
