// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: KKMKKBDBMNB.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from KKMKKBDBMNB.proto</summary>
  public static partial class KKMKKBDBMNBReflection {

    #region Descriptor
    /// <summary>File descriptor for KKMKKBDBMNB.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static KKMKKBDBMNBReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFLS01LS0JEQk1OQi5wcm90byJMCgtLS01LS0JEQk1OQhITCgtKT0tERk9E",
            "TEVQSBgGIAEoDRITCgtNR0VMUE9CRkdJQRgHIAEoDRITCgtDT0JDUEVHREtM",
            "TRgMIAEoCEIeqgIbRWdnTGluay5EYW5oZW5nU2VydmVyLlByb3RvYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.KKMKKBDBMNB), global::EggLink.DanhengServer.Proto.KKMKKBDBMNB.Parser, new[]{ "JOKDFODLEPH", "MGELPOBFGIA", "COBCPEGDKLM" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class KKMKKBDBMNB : pb::IMessage<KKMKKBDBMNB>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<KKMKKBDBMNB> _parser = new pb::MessageParser<KKMKKBDBMNB>(() => new KKMKKBDBMNB());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<KKMKKBDBMNB> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.KKMKKBDBMNBReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KKMKKBDBMNB() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KKMKKBDBMNB(KKMKKBDBMNB other) : this() {
      jOKDFODLEPH_ = other.jOKDFODLEPH_;
      mGELPOBFGIA_ = other.mGELPOBFGIA_;
      cOBCPEGDKLM_ = other.cOBCPEGDKLM_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KKMKKBDBMNB Clone() {
      return new KKMKKBDBMNB(this);
    }

    /// <summary>Field number for the "JOKDFODLEPH" field.</summary>
    public const int JOKDFODLEPHFieldNumber = 6;
    private uint jOKDFODLEPH_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint JOKDFODLEPH {
      get { return jOKDFODLEPH_; }
      set {
        jOKDFODLEPH_ = value;
      }
    }

    /// <summary>Field number for the "MGELPOBFGIA" field.</summary>
    public const int MGELPOBFGIAFieldNumber = 7;
    private uint mGELPOBFGIA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MGELPOBFGIA {
      get { return mGELPOBFGIA_; }
      set {
        mGELPOBFGIA_ = value;
      }
    }

    /// <summary>Field number for the "COBCPEGDKLM" field.</summary>
    public const int COBCPEGDKLMFieldNumber = 12;
    private bool cOBCPEGDKLM_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool COBCPEGDKLM {
      get { return cOBCPEGDKLM_; }
      set {
        cOBCPEGDKLM_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as KKMKKBDBMNB);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(KKMKKBDBMNB other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (JOKDFODLEPH != other.JOKDFODLEPH) return false;
      if (MGELPOBFGIA != other.MGELPOBFGIA) return false;
      if (COBCPEGDKLM != other.COBCPEGDKLM) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (JOKDFODLEPH != 0) hash ^= JOKDFODLEPH.GetHashCode();
      if (MGELPOBFGIA != 0) hash ^= MGELPOBFGIA.GetHashCode();
      if (COBCPEGDKLM != false) hash ^= COBCPEGDKLM.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (JOKDFODLEPH != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(JOKDFODLEPH);
      }
      if (MGELPOBFGIA != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(MGELPOBFGIA);
      }
      if (COBCPEGDKLM != false) {
        output.WriteRawTag(96);
        output.WriteBool(COBCPEGDKLM);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (JOKDFODLEPH != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(JOKDFODLEPH);
      }
      if (MGELPOBFGIA != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(MGELPOBFGIA);
      }
      if (COBCPEGDKLM != false) {
        output.WriteRawTag(96);
        output.WriteBool(COBCPEGDKLM);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (JOKDFODLEPH != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(JOKDFODLEPH);
      }
      if (MGELPOBFGIA != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MGELPOBFGIA);
      }
      if (COBCPEGDKLM != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(KKMKKBDBMNB other) {
      if (other == null) {
        return;
      }
      if (other.JOKDFODLEPH != 0) {
        JOKDFODLEPH = other.JOKDFODLEPH;
      }
      if (other.MGELPOBFGIA != 0) {
        MGELPOBFGIA = other.MGELPOBFGIA;
      }
      if (other.COBCPEGDKLM != false) {
        COBCPEGDKLM = other.COBCPEGDKLM;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 48: {
            JOKDFODLEPH = input.ReadUInt32();
            break;
          }
          case 56: {
            MGELPOBFGIA = input.ReadUInt32();
            break;
          }
          case 96: {
            COBCPEGDKLM = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 48: {
            JOKDFODLEPH = input.ReadUInt32();
            break;
          }
          case 56: {
            MGELPOBFGIA = input.ReadUInt32();
            break;
          }
          case 96: {
            COBCPEGDKLM = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
