// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LGBGFCFGEHG.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from LGBGFCFGEHG.proto</summary>
  public static partial class LGBGFCFGEHGReflection {

    #region Descriptor
    /// <summary>File descriptor for LGBGFCFGEHG.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LGBGFCFGEHGReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFMR0JHRkNGR0VIRy5wcm90bxoRS09HR05NSUVDTVAucHJvdG8aEU5GQkpB",
            "QlBMSU5QLnByb3RvGhFPTkVBRUlNSElNRi5wcm90byK1AQoLTEdCR0ZDRkdF",
            "SEcSEwoLQUlESUNOS09LSk0YASABKA0SEwoLSkxFTEJKTkdCRUIYAiABKA0S",
            "IQoLSUdGQk1BTUlHT0MYBiABKAsyDC5ORkJKQUJQTElOUBIhCgtQQ0hCSkVP",
            "RlBJRRgMIAMoCzIMLk9ORUFFSU1ISU1GEhMKC0lCR01KTkFETUxHGA4gAygN",
            "EiEKC0dHQUtGQkxOS0dEGA8gAygLMgwuS09HR05NSUVDTVBCHqoCG0VnZ0xp",
            "bmsuRGFuaGVuZ1NlcnZlci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.KOGGNMIECMPReflection.Descriptor, global::EggLink.DanhengServer.Proto.NFBJABPLINPReflection.Descriptor, global::EggLink.DanhengServer.Proto.ONEAEIMHIMFReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.LGBGFCFGEHG), global::EggLink.DanhengServer.Proto.LGBGFCFGEHG.Parser, new[]{ "AIDICNKOKJM", "JLELBJNGBEB", "IGFBMAMIGOC", "PCHBJEOFPIE", "IBGMJNADMLG", "GGAKFBLNKGD" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LGBGFCFGEHG : pb::IMessage<LGBGFCFGEHG>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LGBGFCFGEHG> _parser = new pb::MessageParser<LGBGFCFGEHG>(() => new LGBGFCFGEHG());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LGBGFCFGEHG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.LGBGFCFGEHGReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LGBGFCFGEHG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LGBGFCFGEHG(LGBGFCFGEHG other) : this() {
      aIDICNKOKJM_ = other.aIDICNKOKJM_;
      jLELBJNGBEB_ = other.jLELBJNGBEB_;
      iGFBMAMIGOC_ = other.iGFBMAMIGOC_ != null ? other.iGFBMAMIGOC_.Clone() : null;
      pCHBJEOFPIE_ = other.pCHBJEOFPIE_.Clone();
      iBGMJNADMLG_ = other.iBGMJNADMLG_.Clone();
      gGAKFBLNKGD_ = other.gGAKFBLNKGD_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LGBGFCFGEHG Clone() {
      return new LGBGFCFGEHG(this);
    }

    /// <summary>Field number for the "AIDICNKOKJM" field.</summary>
    public const int AIDICNKOKJMFieldNumber = 1;
    private uint aIDICNKOKJM_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AIDICNKOKJM {
      get { return aIDICNKOKJM_; }
      set {
        aIDICNKOKJM_ = value;
      }
    }

    /// <summary>Field number for the "JLELBJNGBEB" field.</summary>
    public const int JLELBJNGBEBFieldNumber = 2;
    private uint jLELBJNGBEB_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint JLELBJNGBEB {
      get { return jLELBJNGBEB_; }
      set {
        jLELBJNGBEB_ = value;
      }
    }

    /// <summary>Field number for the "IGFBMAMIGOC" field.</summary>
    public const int IGFBMAMIGOCFieldNumber = 6;
    private global::EggLink.DanhengServer.Proto.NFBJABPLINP iGFBMAMIGOC_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.NFBJABPLINP IGFBMAMIGOC {
      get { return iGFBMAMIGOC_; }
      set {
        iGFBMAMIGOC_ = value;
      }
    }

    /// <summary>Field number for the "PCHBJEOFPIE" field.</summary>
    public const int PCHBJEOFPIEFieldNumber = 12;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.ONEAEIMHIMF> _repeated_pCHBJEOFPIE_codec
        = pb::FieldCodec.ForMessage(98, global::EggLink.DanhengServer.Proto.ONEAEIMHIMF.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.ONEAEIMHIMF> pCHBJEOFPIE_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.ONEAEIMHIMF>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.ONEAEIMHIMF> PCHBJEOFPIE {
      get { return pCHBJEOFPIE_; }
    }

    /// <summary>Field number for the "IBGMJNADMLG" field.</summary>
    public const int IBGMJNADMLGFieldNumber = 14;
    private static readonly pb::FieldCodec<uint> _repeated_iBGMJNADMLG_codec
        = pb::FieldCodec.ForUInt32(114);
    private readonly pbc::RepeatedField<uint> iBGMJNADMLG_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> IBGMJNADMLG {
      get { return iBGMJNADMLG_; }
    }

    /// <summary>Field number for the "GGAKFBLNKGD" field.</summary>
    public const int GGAKFBLNKGDFieldNumber = 15;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.KOGGNMIECMP> _repeated_gGAKFBLNKGD_codec
        = pb::FieldCodec.ForMessage(122, global::EggLink.DanhengServer.Proto.KOGGNMIECMP.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.KOGGNMIECMP> gGAKFBLNKGD_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.KOGGNMIECMP>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.KOGGNMIECMP> GGAKFBLNKGD {
      get { return gGAKFBLNKGD_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LGBGFCFGEHG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LGBGFCFGEHG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AIDICNKOKJM != other.AIDICNKOKJM) return false;
      if (JLELBJNGBEB != other.JLELBJNGBEB) return false;
      if (!object.Equals(IGFBMAMIGOC, other.IGFBMAMIGOC)) return false;
      if(!pCHBJEOFPIE_.Equals(other.pCHBJEOFPIE_)) return false;
      if(!iBGMJNADMLG_.Equals(other.iBGMJNADMLG_)) return false;
      if(!gGAKFBLNKGD_.Equals(other.gGAKFBLNKGD_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AIDICNKOKJM != 0) hash ^= AIDICNKOKJM.GetHashCode();
      if (JLELBJNGBEB != 0) hash ^= JLELBJNGBEB.GetHashCode();
      if (iGFBMAMIGOC_ != null) hash ^= IGFBMAMIGOC.GetHashCode();
      hash ^= pCHBJEOFPIE_.GetHashCode();
      hash ^= iBGMJNADMLG_.GetHashCode();
      hash ^= gGAKFBLNKGD_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AIDICNKOKJM != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(AIDICNKOKJM);
      }
      if (JLELBJNGBEB != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(JLELBJNGBEB);
      }
      if (iGFBMAMIGOC_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(IGFBMAMIGOC);
      }
      pCHBJEOFPIE_.WriteTo(output, _repeated_pCHBJEOFPIE_codec);
      iBGMJNADMLG_.WriteTo(output, _repeated_iBGMJNADMLG_codec);
      gGAKFBLNKGD_.WriteTo(output, _repeated_gGAKFBLNKGD_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AIDICNKOKJM != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(AIDICNKOKJM);
      }
      if (JLELBJNGBEB != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(JLELBJNGBEB);
      }
      if (iGFBMAMIGOC_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(IGFBMAMIGOC);
      }
      pCHBJEOFPIE_.WriteTo(ref output, _repeated_pCHBJEOFPIE_codec);
      iBGMJNADMLG_.WriteTo(ref output, _repeated_iBGMJNADMLG_codec);
      gGAKFBLNKGD_.WriteTo(ref output, _repeated_gGAKFBLNKGD_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AIDICNKOKJM != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AIDICNKOKJM);
      }
      if (JLELBJNGBEB != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(JLELBJNGBEB);
      }
      if (iGFBMAMIGOC_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(IGFBMAMIGOC);
      }
      size += pCHBJEOFPIE_.CalculateSize(_repeated_pCHBJEOFPIE_codec);
      size += iBGMJNADMLG_.CalculateSize(_repeated_iBGMJNADMLG_codec);
      size += gGAKFBLNKGD_.CalculateSize(_repeated_gGAKFBLNKGD_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LGBGFCFGEHG other) {
      if (other == null) {
        return;
      }
      if (other.AIDICNKOKJM != 0) {
        AIDICNKOKJM = other.AIDICNKOKJM;
      }
      if (other.JLELBJNGBEB != 0) {
        JLELBJNGBEB = other.JLELBJNGBEB;
      }
      if (other.iGFBMAMIGOC_ != null) {
        if (iGFBMAMIGOC_ == null) {
          IGFBMAMIGOC = new global::EggLink.DanhengServer.Proto.NFBJABPLINP();
        }
        IGFBMAMIGOC.MergeFrom(other.IGFBMAMIGOC);
      }
      pCHBJEOFPIE_.Add(other.pCHBJEOFPIE_);
      iBGMJNADMLG_.Add(other.iBGMJNADMLG_);
      gGAKFBLNKGD_.Add(other.gGAKFBLNKGD_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AIDICNKOKJM = input.ReadUInt32();
            break;
          }
          case 16: {
            JLELBJNGBEB = input.ReadUInt32();
            break;
          }
          case 50: {
            if (iGFBMAMIGOC_ == null) {
              IGFBMAMIGOC = new global::EggLink.DanhengServer.Proto.NFBJABPLINP();
            }
            input.ReadMessage(IGFBMAMIGOC);
            break;
          }
          case 98: {
            pCHBJEOFPIE_.AddEntriesFrom(input, _repeated_pCHBJEOFPIE_codec);
            break;
          }
          case 114:
          case 112: {
            iBGMJNADMLG_.AddEntriesFrom(input, _repeated_iBGMJNADMLG_codec);
            break;
          }
          case 122: {
            gGAKFBLNKGD_.AddEntriesFrom(input, _repeated_gGAKFBLNKGD_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AIDICNKOKJM = input.ReadUInt32();
            break;
          }
          case 16: {
            JLELBJNGBEB = input.ReadUInt32();
            break;
          }
          case 50: {
            if (iGFBMAMIGOC_ == null) {
              IGFBMAMIGOC = new global::EggLink.DanhengServer.Proto.NFBJABPLINP();
            }
            input.ReadMessage(IGFBMAMIGOC);
            break;
          }
          case 98: {
            pCHBJEOFPIE_.AddEntriesFrom(ref input, _repeated_pCHBJEOFPIE_codec);
            break;
          }
          case 114:
          case 112: {
            iBGMJNADMLG_.AddEntriesFrom(ref input, _repeated_iBGMJNADMLG_codec);
            break;
          }
          case 122: {
            gGAKFBLNKGD_.AddEntriesFrom(ref input, _repeated_gGAKFBLNKGD_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
