// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LKDJMKJCGFO.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from LKDJMKJCGFO.proto</summary>
  public static partial class LKDJMKJCGFOReflection {

    #region Descriptor
    /// <summary>File descriptor for LKDJMKJCGFO.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LKDJMKJCGFOReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFMS0RKTUtKQ0dGTy5wcm90byKLAQoLTEtESk1LSkNHRk8SEwoLTE5OUEVO",
            "QUxNSkYYAiADKA0SEwoLRExFSkpMT05DSkYYAyABKA0SEwoLSExPT0ZPQUZG",
            "TEIYBCABKAgSEwoLSlBGRU1PUE5KQkwYBiADKA0SEwoLTEZDQk9CRk1KTk8Y",
            "ByABKA0SEwoLTlBFRFBGTU5LSVAYCyABKA1CHqoCG0VnZ0xpbmsuRGFuaGVu",
            "Z1NlcnZlci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.LKDJMKJCGFO), global::EggLink.DanhengServer.Proto.LKDJMKJCGFO.Parser, new[]{ "LNNPENALMJF", "DLEJJLONCJF", "HLOOFOAFFLB", "JPFEMOPNJBL", "LFCBOBFMJNO", "NPEDPFMNKIP" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LKDJMKJCGFO : pb::IMessage<LKDJMKJCGFO>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LKDJMKJCGFO> _parser = new pb::MessageParser<LKDJMKJCGFO>(() => new LKDJMKJCGFO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LKDJMKJCGFO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.LKDJMKJCGFOReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LKDJMKJCGFO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LKDJMKJCGFO(LKDJMKJCGFO other) : this() {
      lNNPENALMJF_ = other.lNNPENALMJF_.Clone();
      dLEJJLONCJF_ = other.dLEJJLONCJF_;
      hLOOFOAFFLB_ = other.hLOOFOAFFLB_;
      jPFEMOPNJBL_ = other.jPFEMOPNJBL_.Clone();
      lFCBOBFMJNO_ = other.lFCBOBFMJNO_;
      nPEDPFMNKIP_ = other.nPEDPFMNKIP_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LKDJMKJCGFO Clone() {
      return new LKDJMKJCGFO(this);
    }

    /// <summary>Field number for the "LNNPENALMJF" field.</summary>
    public const int LNNPENALMJFFieldNumber = 2;
    private static readonly pb::FieldCodec<uint> _repeated_lNNPENALMJF_codec
        = pb::FieldCodec.ForUInt32(18);
    private readonly pbc::RepeatedField<uint> lNNPENALMJF_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> LNNPENALMJF {
      get { return lNNPENALMJF_; }
    }

    /// <summary>Field number for the "DLEJJLONCJF" field.</summary>
    public const int DLEJJLONCJFFieldNumber = 3;
    private uint dLEJJLONCJF_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DLEJJLONCJF {
      get { return dLEJJLONCJF_; }
      set {
        dLEJJLONCJF_ = value;
      }
    }

    /// <summary>Field number for the "HLOOFOAFFLB" field.</summary>
    public const int HLOOFOAFFLBFieldNumber = 4;
    private bool hLOOFOAFFLB_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HLOOFOAFFLB {
      get { return hLOOFOAFFLB_; }
      set {
        hLOOFOAFFLB_ = value;
      }
    }

    /// <summary>Field number for the "JPFEMOPNJBL" field.</summary>
    public const int JPFEMOPNJBLFieldNumber = 6;
    private static readonly pb::FieldCodec<uint> _repeated_jPFEMOPNJBL_codec
        = pb::FieldCodec.ForUInt32(50);
    private readonly pbc::RepeatedField<uint> jPFEMOPNJBL_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> JPFEMOPNJBL {
      get { return jPFEMOPNJBL_; }
    }

    /// <summary>Field number for the "LFCBOBFMJNO" field.</summary>
    public const int LFCBOBFMJNOFieldNumber = 7;
    private uint lFCBOBFMJNO_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LFCBOBFMJNO {
      get { return lFCBOBFMJNO_; }
      set {
        lFCBOBFMJNO_ = value;
      }
    }

    /// <summary>Field number for the "NPEDPFMNKIP" field.</summary>
    public const int NPEDPFMNKIPFieldNumber = 11;
    private uint nPEDPFMNKIP_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NPEDPFMNKIP {
      get { return nPEDPFMNKIP_; }
      set {
        nPEDPFMNKIP_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LKDJMKJCGFO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LKDJMKJCGFO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!lNNPENALMJF_.Equals(other.lNNPENALMJF_)) return false;
      if (DLEJJLONCJF != other.DLEJJLONCJF) return false;
      if (HLOOFOAFFLB != other.HLOOFOAFFLB) return false;
      if(!jPFEMOPNJBL_.Equals(other.jPFEMOPNJBL_)) return false;
      if (LFCBOBFMJNO != other.LFCBOBFMJNO) return false;
      if (NPEDPFMNKIP != other.NPEDPFMNKIP) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= lNNPENALMJF_.GetHashCode();
      if (DLEJJLONCJF != 0) hash ^= DLEJJLONCJF.GetHashCode();
      if (HLOOFOAFFLB != false) hash ^= HLOOFOAFFLB.GetHashCode();
      hash ^= jPFEMOPNJBL_.GetHashCode();
      if (LFCBOBFMJNO != 0) hash ^= LFCBOBFMJNO.GetHashCode();
      if (NPEDPFMNKIP != 0) hash ^= NPEDPFMNKIP.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      lNNPENALMJF_.WriteTo(output, _repeated_lNNPENALMJF_codec);
      if (DLEJJLONCJF != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(DLEJJLONCJF);
      }
      if (HLOOFOAFFLB != false) {
        output.WriteRawTag(32);
        output.WriteBool(HLOOFOAFFLB);
      }
      jPFEMOPNJBL_.WriteTo(output, _repeated_jPFEMOPNJBL_codec);
      if (LFCBOBFMJNO != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(LFCBOBFMJNO);
      }
      if (NPEDPFMNKIP != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(NPEDPFMNKIP);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      lNNPENALMJF_.WriteTo(ref output, _repeated_lNNPENALMJF_codec);
      if (DLEJJLONCJF != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(DLEJJLONCJF);
      }
      if (HLOOFOAFFLB != false) {
        output.WriteRawTag(32);
        output.WriteBool(HLOOFOAFFLB);
      }
      jPFEMOPNJBL_.WriteTo(ref output, _repeated_jPFEMOPNJBL_codec);
      if (LFCBOBFMJNO != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(LFCBOBFMJNO);
      }
      if (NPEDPFMNKIP != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(NPEDPFMNKIP);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += lNNPENALMJF_.CalculateSize(_repeated_lNNPENALMJF_codec);
      if (DLEJJLONCJF != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DLEJJLONCJF);
      }
      if (HLOOFOAFFLB != false) {
        size += 1 + 1;
      }
      size += jPFEMOPNJBL_.CalculateSize(_repeated_jPFEMOPNJBL_codec);
      if (LFCBOBFMJNO != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LFCBOBFMJNO);
      }
      if (NPEDPFMNKIP != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NPEDPFMNKIP);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LKDJMKJCGFO other) {
      if (other == null) {
        return;
      }
      lNNPENALMJF_.Add(other.lNNPENALMJF_);
      if (other.DLEJJLONCJF != 0) {
        DLEJJLONCJF = other.DLEJJLONCJF;
      }
      if (other.HLOOFOAFFLB != false) {
        HLOOFOAFFLB = other.HLOOFOAFFLB;
      }
      jPFEMOPNJBL_.Add(other.jPFEMOPNJBL_);
      if (other.LFCBOBFMJNO != 0) {
        LFCBOBFMJNO = other.LFCBOBFMJNO;
      }
      if (other.NPEDPFMNKIP != 0) {
        NPEDPFMNKIP = other.NPEDPFMNKIP;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18:
          case 16: {
            lNNPENALMJF_.AddEntriesFrom(input, _repeated_lNNPENALMJF_codec);
            break;
          }
          case 24: {
            DLEJJLONCJF = input.ReadUInt32();
            break;
          }
          case 32: {
            HLOOFOAFFLB = input.ReadBool();
            break;
          }
          case 50:
          case 48: {
            jPFEMOPNJBL_.AddEntriesFrom(input, _repeated_jPFEMOPNJBL_codec);
            break;
          }
          case 56: {
            LFCBOBFMJNO = input.ReadUInt32();
            break;
          }
          case 88: {
            NPEDPFMNKIP = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18:
          case 16: {
            lNNPENALMJF_.AddEntriesFrom(ref input, _repeated_lNNPENALMJF_codec);
            break;
          }
          case 24: {
            DLEJJLONCJF = input.ReadUInt32();
            break;
          }
          case 32: {
            HLOOFOAFFLB = input.ReadBool();
            break;
          }
          case 50:
          case 48: {
            jPFEMOPNJBL_.AddEntriesFrom(ref input, _repeated_jPFEMOPNJBL_codec);
            break;
          }
          case 56: {
            LFCBOBFMJNO = input.ReadUInt32();
            break;
          }
          case 88: {
            NPEDPFMNKIP = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
