// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PlanetFesDealAvatarEventOptionItemScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from PlanetFesDealAvatarEventOptionItemScRsp.proto</summary>
  public static partial class PlanetFesDealAvatarEventOptionItemScRspReflection {

    #region Descriptor
    /// <summary>File descriptor for PlanetFesDealAvatarEventOptionItemScRsp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlanetFesDealAvatarEventOptionItemScRspReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci1QbGFuZXRGZXNEZWFsQXZhdGFyRXZlbnRPcHRpb25JdGVtU2NSc3AucHJv",
            "dG8aFVBsYW5ldEZlc1Jld2FyZC5wcm90bxoRSk9GR0RBSUFEQk8ucHJvdG8i",
            "vgEKJ1BsYW5ldEZlc0RlYWxBdmF0YXJFdmVudE9wdGlvbkl0ZW1TY1JzcBIT",
            "CgtIQUtLR09ESUNGSRgHIAEoDRITCgtMRUNESEREQ0VJQRgJIAEoCBIPCgdy",
            "ZXRjb2RlGA8gASgNEhMKC09KS0pQS0hERVBFGA0gASgNEiEKC05GSkxGTkJQ",
            "UFBHGA4gASgLMgwuSk9GR0RBSUFEQk8SIAoGcmV3YXJkGAQgASgLMhAuUGxh",
            "bmV0RmVzUmV3YXJkQh6qAhtFZ2dMaW5rLkRhbmhlbmdTZXJ2ZXIuUHJvdG9i",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.PlanetFesRewardReflection.Descriptor, global::EggLink.DanhengServer.Proto.JOFGDAIADBOReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.PlanetFesDealAvatarEventOptionItemScRsp), global::EggLink.DanhengServer.Proto.PlanetFesDealAvatarEventOptionItemScRsp.Parser, new[]{ "HAKKGODICFI", "LECDHDDCEIA", "Retcode", "OJKJPKHDEPE", "NFJLFNBPPPG", "Reward" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PlanetFesDealAvatarEventOptionItemScRsp : pb::IMessage<PlanetFesDealAvatarEventOptionItemScRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlanetFesDealAvatarEventOptionItemScRsp> _parser = new pb::MessageParser<PlanetFesDealAvatarEventOptionItemScRsp>(() => new PlanetFesDealAvatarEventOptionItemScRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlanetFesDealAvatarEventOptionItemScRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.PlanetFesDealAvatarEventOptionItemScRspReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlanetFesDealAvatarEventOptionItemScRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlanetFesDealAvatarEventOptionItemScRsp(PlanetFesDealAvatarEventOptionItemScRsp other) : this() {
      hAKKGODICFI_ = other.hAKKGODICFI_;
      lECDHDDCEIA_ = other.lECDHDDCEIA_;
      retcode_ = other.retcode_;
      oJKJPKHDEPE_ = other.oJKJPKHDEPE_;
      nFJLFNBPPPG_ = other.nFJLFNBPPPG_ != null ? other.nFJLFNBPPPG_.Clone() : null;
      reward_ = other.reward_ != null ? other.reward_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlanetFesDealAvatarEventOptionItemScRsp Clone() {
      return new PlanetFesDealAvatarEventOptionItemScRsp(this);
    }

    /// <summary>Field number for the "HAKKGODICFI" field.</summary>
    public const int HAKKGODICFIFieldNumber = 7;
    private uint hAKKGODICFI_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint HAKKGODICFI {
      get { return hAKKGODICFI_; }
      set {
        hAKKGODICFI_ = value;
      }
    }

    /// <summary>Field number for the "LECDHDDCEIA" field.</summary>
    public const int LECDHDDCEIAFieldNumber = 9;
    private bool lECDHDDCEIA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool LECDHDDCEIA {
      get { return lECDHDDCEIA_; }
      set {
        lECDHDDCEIA_ = value;
      }
    }

    /// <summary>Field number for the "retcode" field.</summary>
    public const int RetcodeFieldNumber = 15;
    private uint retcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Retcode {
      get { return retcode_; }
      set {
        retcode_ = value;
      }
    }

    /// <summary>Field number for the "OJKJPKHDEPE" field.</summary>
    public const int OJKJPKHDEPEFieldNumber = 13;
    private uint oJKJPKHDEPE_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint OJKJPKHDEPE {
      get { return oJKJPKHDEPE_; }
      set {
        oJKJPKHDEPE_ = value;
      }
    }

    /// <summary>Field number for the "NFJLFNBPPPG" field.</summary>
    public const int NFJLFNBPPPGFieldNumber = 14;
    private global::EggLink.DanhengServer.Proto.JOFGDAIADBO nFJLFNBPPPG_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.JOFGDAIADBO NFJLFNBPPPG {
      get { return nFJLFNBPPPG_; }
      set {
        nFJLFNBPPPG_ = value;
      }
    }

    /// <summary>Field number for the "reward" field.</summary>
    public const int RewardFieldNumber = 4;
    private global::EggLink.DanhengServer.Proto.PlanetFesReward reward_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.PlanetFesReward Reward {
      get { return reward_; }
      set {
        reward_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlanetFesDealAvatarEventOptionItemScRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlanetFesDealAvatarEventOptionItemScRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (HAKKGODICFI != other.HAKKGODICFI) return false;
      if (LECDHDDCEIA != other.LECDHDDCEIA) return false;
      if (Retcode != other.Retcode) return false;
      if (OJKJPKHDEPE != other.OJKJPKHDEPE) return false;
      if (!object.Equals(NFJLFNBPPPG, other.NFJLFNBPPPG)) return false;
      if (!object.Equals(Reward, other.Reward)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HAKKGODICFI != 0) hash ^= HAKKGODICFI.GetHashCode();
      if (LECDHDDCEIA != false) hash ^= LECDHDDCEIA.GetHashCode();
      if (Retcode != 0) hash ^= Retcode.GetHashCode();
      if (OJKJPKHDEPE != 0) hash ^= OJKJPKHDEPE.GetHashCode();
      if (nFJLFNBPPPG_ != null) hash ^= NFJLFNBPPPG.GetHashCode();
      if (reward_ != null) hash ^= Reward.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (reward_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Reward);
      }
      if (HAKKGODICFI != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(HAKKGODICFI);
      }
      if (LECDHDDCEIA != false) {
        output.WriteRawTag(72);
        output.WriteBool(LECDHDDCEIA);
      }
      if (OJKJPKHDEPE != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(OJKJPKHDEPE);
      }
      if (nFJLFNBPPPG_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(NFJLFNBPPPG);
      }
      if (Retcode != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(Retcode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (reward_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Reward);
      }
      if (HAKKGODICFI != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(HAKKGODICFI);
      }
      if (LECDHDDCEIA != false) {
        output.WriteRawTag(72);
        output.WriteBool(LECDHDDCEIA);
      }
      if (OJKJPKHDEPE != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(OJKJPKHDEPE);
      }
      if (nFJLFNBPPPG_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(NFJLFNBPPPG);
      }
      if (Retcode != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(Retcode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HAKKGODICFI != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HAKKGODICFI);
      }
      if (LECDHDDCEIA != false) {
        size += 1 + 1;
      }
      if (Retcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Retcode);
      }
      if (OJKJPKHDEPE != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(OJKJPKHDEPE);
      }
      if (nFJLFNBPPPG_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NFJLFNBPPPG);
      }
      if (reward_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Reward);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlanetFesDealAvatarEventOptionItemScRsp other) {
      if (other == null) {
        return;
      }
      if (other.HAKKGODICFI != 0) {
        HAKKGODICFI = other.HAKKGODICFI;
      }
      if (other.LECDHDDCEIA != false) {
        LECDHDDCEIA = other.LECDHDDCEIA;
      }
      if (other.Retcode != 0) {
        Retcode = other.Retcode;
      }
      if (other.OJKJPKHDEPE != 0) {
        OJKJPKHDEPE = other.OJKJPKHDEPE;
      }
      if (other.nFJLFNBPPPG_ != null) {
        if (nFJLFNBPPPG_ == null) {
          NFJLFNBPPPG = new global::EggLink.DanhengServer.Proto.JOFGDAIADBO();
        }
        NFJLFNBPPPG.MergeFrom(other.NFJLFNBPPPG);
      }
      if (other.reward_ != null) {
        if (reward_ == null) {
          Reward = new global::EggLink.DanhengServer.Proto.PlanetFesReward();
        }
        Reward.MergeFrom(other.Reward);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 34: {
            if (reward_ == null) {
              Reward = new global::EggLink.DanhengServer.Proto.PlanetFesReward();
            }
            input.ReadMessage(Reward);
            break;
          }
          case 56: {
            HAKKGODICFI = input.ReadUInt32();
            break;
          }
          case 72: {
            LECDHDDCEIA = input.ReadBool();
            break;
          }
          case 104: {
            OJKJPKHDEPE = input.ReadUInt32();
            break;
          }
          case 114: {
            if (nFJLFNBPPPG_ == null) {
              NFJLFNBPPPG = new global::EggLink.DanhengServer.Proto.JOFGDAIADBO();
            }
            input.ReadMessage(NFJLFNBPPPG);
            break;
          }
          case 120: {
            Retcode = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 34: {
            if (reward_ == null) {
              Reward = new global::EggLink.DanhengServer.Proto.PlanetFesReward();
            }
            input.ReadMessage(Reward);
            break;
          }
          case 56: {
            HAKKGODICFI = input.ReadUInt32();
            break;
          }
          case 72: {
            LECDHDDCEIA = input.ReadBool();
            break;
          }
          case 104: {
            OJKJPKHDEPE = input.ReadUInt32();
            break;
          }
          case 114: {
            if (nFJLFNBPPPG_ == null) {
              NFJLFNBPPPG = new global::EggLink.DanhengServer.Proto.JOFGDAIADBO();
            }
            input.ReadMessage(NFJLFNBPPPG);
            break;
          }
          case 120: {
            Retcode = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
