// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PMAOJCBKAFI.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from PMAOJCBKAFI.proto</summary>
  public static partial class PMAOJCBKAFIReflection {

    #region Descriptor
    /// <summary>File descriptor for PMAOJCBKAFI.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PMAOJCBKAFIReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFQTUFPSkNCS0FGSS5wcm90byK0AQoLUE1BT0pDQktBRkkSEwoLQUNJQUhM",
            "R0VITUQYAyABKA0SMgoLQklPSlBERUJCREsYCiADKAsyHS5QTUFPSkNCS0FG",
            "SS5CSU9KUERFQkJES0VudHJ5EhMKC0ZFSkRGR0lPT0hPGAsgASgNEhMKC0hC",
            "SENQR09JSUtJGA8gASgNGjIKEEJJT0pQREVCQkRLRW50cnkSCwoDa2V5GAEg",
            "ASgNEg0KBXZhbHVlGAIgASgNOgI4AUIeqgIbRWdnTGluay5EYW5oZW5nU2Vy",
            "dmVyLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.PMAOJCBKAFI), global::EggLink.DanhengServer.Proto.PMAOJCBKAFI.Parser, new[]{ "ACIAHLGEHMD", "BIOJPDEBBDK", "FEJDFGIOOHO", "HBHCPGOIIKI" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PMAOJCBKAFI : pb::IMessage<PMAOJCBKAFI>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PMAOJCBKAFI> _parser = new pb::MessageParser<PMAOJCBKAFI>(() => new PMAOJCBKAFI());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PMAOJCBKAFI> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.PMAOJCBKAFIReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PMAOJCBKAFI() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PMAOJCBKAFI(PMAOJCBKAFI other) : this() {
      aCIAHLGEHMD_ = other.aCIAHLGEHMD_;
      bIOJPDEBBDK_ = other.bIOJPDEBBDK_.Clone();
      fEJDFGIOOHO_ = other.fEJDFGIOOHO_;
      hBHCPGOIIKI_ = other.hBHCPGOIIKI_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PMAOJCBKAFI Clone() {
      return new PMAOJCBKAFI(this);
    }

    /// <summary>Field number for the "ACIAHLGEHMD" field.</summary>
    public const int ACIAHLGEHMDFieldNumber = 3;
    private uint aCIAHLGEHMD_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ACIAHLGEHMD {
      get { return aCIAHLGEHMD_; }
      set {
        aCIAHLGEHMD_ = value;
      }
    }

    /// <summary>Field number for the "BIOJPDEBBDK" field.</summary>
    public const int BIOJPDEBBDKFieldNumber = 10;
    private static readonly pbc::MapField<uint, uint>.Codec _map_bIOJPDEBBDK_codec
        = new pbc::MapField<uint, uint>.Codec(pb::FieldCodec.ForUInt32(8, 0), pb::FieldCodec.ForUInt32(16, 0), 82);
    private readonly pbc::MapField<uint, uint> bIOJPDEBBDK_ = new pbc::MapField<uint, uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<uint, uint> BIOJPDEBBDK {
      get { return bIOJPDEBBDK_; }
    }

    /// <summary>Field number for the "FEJDFGIOOHO" field.</summary>
    public const int FEJDFGIOOHOFieldNumber = 11;
    private uint fEJDFGIOOHO_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FEJDFGIOOHO {
      get { return fEJDFGIOOHO_; }
      set {
        fEJDFGIOOHO_ = value;
      }
    }

    /// <summary>Field number for the "HBHCPGOIIKI" field.</summary>
    public const int HBHCPGOIIKIFieldNumber = 15;
    private uint hBHCPGOIIKI_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint HBHCPGOIIKI {
      get { return hBHCPGOIIKI_; }
      set {
        hBHCPGOIIKI_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PMAOJCBKAFI);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PMAOJCBKAFI other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ACIAHLGEHMD != other.ACIAHLGEHMD) return false;
      if (!BIOJPDEBBDK.Equals(other.BIOJPDEBBDK)) return false;
      if (FEJDFGIOOHO != other.FEJDFGIOOHO) return false;
      if (HBHCPGOIIKI != other.HBHCPGOIIKI) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ACIAHLGEHMD != 0) hash ^= ACIAHLGEHMD.GetHashCode();
      hash ^= BIOJPDEBBDK.GetHashCode();
      if (FEJDFGIOOHO != 0) hash ^= FEJDFGIOOHO.GetHashCode();
      if (HBHCPGOIIKI != 0) hash ^= HBHCPGOIIKI.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ACIAHLGEHMD != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(ACIAHLGEHMD);
      }
      bIOJPDEBBDK_.WriteTo(output, _map_bIOJPDEBBDK_codec);
      if (FEJDFGIOOHO != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(FEJDFGIOOHO);
      }
      if (HBHCPGOIIKI != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(HBHCPGOIIKI);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ACIAHLGEHMD != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(ACIAHLGEHMD);
      }
      bIOJPDEBBDK_.WriteTo(ref output, _map_bIOJPDEBBDK_codec);
      if (FEJDFGIOOHO != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(FEJDFGIOOHO);
      }
      if (HBHCPGOIIKI != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(HBHCPGOIIKI);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ACIAHLGEHMD != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ACIAHLGEHMD);
      }
      size += bIOJPDEBBDK_.CalculateSize(_map_bIOJPDEBBDK_codec);
      if (FEJDFGIOOHO != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FEJDFGIOOHO);
      }
      if (HBHCPGOIIKI != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HBHCPGOIIKI);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PMAOJCBKAFI other) {
      if (other == null) {
        return;
      }
      if (other.ACIAHLGEHMD != 0) {
        ACIAHLGEHMD = other.ACIAHLGEHMD;
      }
      bIOJPDEBBDK_.MergeFrom(other.bIOJPDEBBDK_);
      if (other.FEJDFGIOOHO != 0) {
        FEJDFGIOOHO = other.FEJDFGIOOHO;
      }
      if (other.HBHCPGOIIKI != 0) {
        HBHCPGOIIKI = other.HBHCPGOIIKI;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 24: {
            ACIAHLGEHMD = input.ReadUInt32();
            break;
          }
          case 82: {
            bIOJPDEBBDK_.AddEntriesFrom(input, _map_bIOJPDEBBDK_codec);
            break;
          }
          case 88: {
            FEJDFGIOOHO = input.ReadUInt32();
            break;
          }
          case 120: {
            HBHCPGOIIKI = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 24: {
            ACIAHLGEHMD = input.ReadUInt32();
            break;
          }
          case 82: {
            bIOJPDEBBDK_.AddEntriesFrom(ref input, _map_bIOJPDEBBDK_codec);
            break;
          }
          case 88: {
            FEJDFGIOOHO = input.ReadUInt32();
            break;
          }
          case 120: {
            HBHCPGOIIKI = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
